// ============== VARIABLE PER SERVER =============
// ACE Advanced Ballistics
force force ace_advanced_ballistics_ammoTemperatureEnabled = true;
force force ace_advanced_ballistics_barrelLengthInfluenceEnabled = true;
force force ace_advanced_ballistics_bulletTraceEnabled = true;
force force ace_advanced_ballistics_enabled = true;
force force ace_advanced_ballistics_muzzleVelocityVariationEnabled = true;
force force ace_advanced_ballistics_simulationInterval = 0.05;

// ACE Advanced Fatigue
force force ace_advanced_fatigue_enabled = true;
force force ace_advanced_fatigue_enableStaminaBar = true;
force force ace_advanced_fatigue_fadeStaminaBar = true;
force force ace_advanced_fatigue_loadFactor = 0.4;
force force ace_advanced_fatigue_performanceFactor = 4;
force force ace_advanced_fatigue_recoveryFactor = 5;
force force ace_advanced_fatigue_terrainGradientFactor = 0.7;

// ACE Advanced Throwing
force force ace_advanced_throwing_enabled = true;
force force ace_advanced_throwing_enablePickUp = true;
force force ace_advanced_throwing_enablePickUpAttached = true;
ace_advanced_throwing_enableTempWindInfo = true;
force force ace_advanced_throwing_showMouseControls = true;
force force ace_advanced_throwing_showThrowArc = true;

// ACE Advanced Vehicle Damage
force ace_vehicle_damage_enableCarDamage = false;
force ace_vehicle_damage_enabled = false;

// ACE AI
force ace_ai_assignNVG = false;

// ACE Arsenal
force force ace_arsenal_allowDefaultLoadouts = true;
force force ace_arsenal_allowSharedLoadouts = true;
ace_arsenal_camInverted = false;
ace_arsenal_defaultToFavorites = false;
force force ace_arsenal_enableIdentityTabs = true;
ace_arsenal_enableModIcons = 1;
ace_arsenal_EnableRPTLog = false;
ace_arsenal_favoritesColor = [0.9,0.875,0.6];
ace_arsenal_fontHeight = 4.5;
ace_arsenal_loadoutsSaveFace = false;
ace_arsenal_loadoutsSaveInsignia = true;
ace_arsenal_loadoutsSaveVoice = false;
ace_arsenal_showUnavailableItems = 0;

// ACE Artillery
force force ace_artillerytables_advancedCorrections = true;
force force ace_artillerytables_disableArtilleryComputer = false;
force force ace_mk6mortar_airResistanceEnabled = true;
force force ace_mk6mortar_allowCompass = true;
force force ace_mk6mortar_allowComputerRangefinder = true;
force force ace_mk6mortar_useAmmoHandling = false;

// ACE Captives
force force ace_captives_allowHandcuffOwnSide = true;
force force ace_captives_allowSurrender = true;
force force ace_captives_requireSurrender = 0;
force force ace_captives_requireSurrenderAi = false;

// ACE Casings
ace_casings_enabled = true;
ace_casings_maxCasings = 250;

// ACE Common
force ace_common_allowFadeMusic = true;
force ace_common_checkExtensions = false;
force force ace_common_checkPBOsAction = 0;
force force ace_common_checkPBOsCheckAll = false;
force ace_common_checkPBOsWhitelist = "[]";
force ace_common_deployedSwayFactor = 0;
ace_common_displayTextColor = [0,0,0,0.1];
ace_common_displayTextFontColor = [1,1,1,1];
force ace_common_enableSway = true;
ace_common_epilepsyFriendlyMode = false;
force ace_common_magneticDeclination = false;
ace_common_progressBarInfo = 2;
force ace_common_restedSwayFactor = 0.1;
ace_common_settingFeedbackIcons = 1;
ace_common_settingProgressBarLocation = 0;
force ace_common_swayFactor = 0.3;

// ACE Cook-off
force force ace_cookoff_ammoCookoffDuration = 0.5;
force force ace_cookoff_cookoffDuration = 0.5;
force force ace_cookoff_destroyVehicleAfterCookoff = true;
force force ace_cookoff_enableAmmobox = false;
force force ace_cookoff_enableAmmoCookoff = false;
force force ace_cookoff_enableFire = false;
force force ace_cookoff_probabilityCoef = 0.5;
force force ace_cookoff_removeAmmoDuringCookoff = true;

// ACE Crew Served Weapons
force force ace_csw_ammoHandling = 1;
force force ace_csw_defaultAssemblyMode = true;
force force ace_csw_dragAfterDeploy = true;
force force ace_csw_handleExtraMagazines = false;
force ace_csw_handleExtraMagazinesType = 0;
force force ace_csw_progressBarTimeCoefficent = 1;

// ACE Dragging
force ace_dragging_allowRunWithLightweight = true;
ace_dragging_dragAndFire = true;
force ace_dragging_skipContainerWeight = false;
force ace_dragging_weightCoefficient = 1;

// ACE Explosives
ace_explosives_customTimerDefault = 30;
force ace_explosives_customTimerMax = 900;
force ace_explosives_customTimerMin = 5;
force force ace_explosives_explodeOnDefuse = true;
force force ace_explosives_punishNonSpecialists = true;
force force ace_explosives_requireSpecialist = false;

// ACE Field Rations
force ace_field_rations_zeusUpdates = false;
force acex_field_rations_affectAdvancedFatigue = true;
force acex_field_rations_enabled = false;
acex_field_rations_hudShowLevel = 0;
acex_field_rations_hudTransparency = -1;
acex_field_rations_hudType = 0;
force acex_field_rations_hungerSatiated = 1;
force acex_field_rations_nearDepletedConsequence = 1;
force acex_field_rations_terrainObjectActions = true;
force acex_field_rations_thirstQuenched = 1;
force acex_field_rations_timeWithoutFood = 2;
force acex_field_rations_timeWithoutWater = 2;
force acex_field_rations_waterSourceActions = 2;

// ACE Fire
force force ace_fire_dropWeapon = 1;
force force ace_fire_enabled = false;
force force ace_fire_enableFlare = false;
force force ace_fire_enableScreams = false;

// ACE Fortify
force ace_fortify_markObjectsOnMap = 1;
force ace_fortify_timeCostCoefficient = 1;
force ace_fortify_timeMin = 1.5;
force force acex_fortify_settingHint = 2;

// ACE Fragmentation Simulation
force force ace_frag_enabled = false;
force force ace_frag_reflectionsEnabled = false;
force force ace_frag_spallEnabled = false;
force force ace_frag_spallIntensity = 0.5;

// ACE G-Forces
force ace_gforces_coef = 1;
force force ace_gforces_enabledFor = 0;

// ACE Goggles
ace_goggles_drawOverlay = true;
force force ace_goggles_effects = 2;
force force ace_goggles_showClearGlasses = true;
ace_goggles_showInThirdPerson = false;

// ACE Grenades
force ace_grenades_convertExplosives = true;

// ACE Headless
force force acex_headless_delay = 10;
force force acex_headless_enabled = false;
force force acex_headless_endMission = 0;
force force acex_headless_log = true;
force force acex_headless_transferLoadout = 0;

// ACE Hearing
force ace_hearing_autoAddEarplugsToUnits = 1;
ace_hearing_disableEarRinging = false;
force force ace_hearing_earplugsVolume = 0.5;
force ace_hearing_enableCombatDeafness = true;
force ace_hearing_enabledForZeusUnits = false;
ace_hearing_enableNoiseDucking = true;
force ace_hearing_explosionDeafnessCoefficient = 0.3;
force force ace_hearing_unconsciousnessVolume = 0.4;

// ACE Interaction
force force ace_interaction_disableNegativeRating = true;
force ace_interaction_enableAnimActions = true;
force ace_interaction_enableGroupRenaming = true;
force force ace_interaction_enableMagazinePassing = true;
force force ace_interaction_enableTeamManagement = true;
ace_interaction_enableThrowablePassing = true;
ace_interaction_enableWeaponAttachments = true;
force ace_interaction_interactWithEnemyCrew = 0;
force ace_interaction_interactWithTerrainObjects = false;
force ace_interaction_remoteTeamManagement = true;

// ACE Interaction Menu
ace_gestures_showOnInteractionMenu = 2;
ace_interact_menu_actionOnKeyRelease = true;
ace_interact_menu_addBuildingActions = true;
ace_interact_menu_alwaysUseCursorInteraction = true;
ace_interact_menu_alwaysUseCursorSelfInteraction = true;
ace_interact_menu_colorShadowMax = [0,0,0,1];
ace_interact_menu_colorShadowMin = [0,0,0,0.25];
ace_interact_menu_colorTextMax = [1,1,1,1];
ace_interact_menu_colorTextMin = [1,1,1,0.25];
ace_interact_menu_consolidateSingleChild = false;
ace_interact_menu_cursorKeepCentered = false;
ace_interact_menu_cursorKeepCenteredSelfInteraction = false;
ace_interact_menu_menuAnimationSpeed = 0;
ace_interact_menu_menuBackground = 0;
ace_interact_menu_menuBackgroundSelf = 0;
ace_interact_menu_selectorColor = [1,0,0];
ace_interact_menu_shadowSetting = 2;
ace_interact_menu_textSize = 2;
ace_interact_menu_useListMenu = false;
ace_interact_menu_useListMenuSelf = false;

// ACE Interaction Menu (Self) - More
ace_interact_menu_more__ACE_CheckAirTemperature = false;
ace_interact_menu_more__ace_csw_deploy = false;
ace_interact_menu_more__ACE_Equipment = false;
ace_interact_menu_more__ACE_Explosives = false;
ace_interact_menu_more__ace_field_rations = false;
ace_interact_menu_more__ace_fortify = false;
ace_interact_menu_more__ace_gestures = false;
ace_interact_menu_more__ace_intelitems = false;
ace_interact_menu_more__ACE_MapFlashlight = false;
ace_interact_menu_more__ACE_MapGpsHide = false;
ace_interact_menu_more__ACE_MapGpsShow = false;
ace_interact_menu_more__ACE_MapTools = false;
ace_interact_menu_more__ACE_Medical = false;
ace_interact_menu_more__ace_medical_ai_heal = false;
ace_interact_menu_more__ACE_Medical_Menu = false;
ace_interact_menu_more__ACE_MoveRallypoint = false;
ace_interact_menu_more__ACE_PlottingBoard = false;
ace_interact_menu_more__ACE_PlottingBoardHide = false;
ace_interact_menu_more__ACE_RepackMagazines = false;
ace_interact_menu_more__ace_sandbag_place = false;
ace_interact_menu_more__ACE_StartSurrenderingSelf = false;
ace_interact_menu_more__ACE_StopEscortingSelf = false;
ace_interact_menu_more__ACE_StopSurrenderingSelf = false;
ace_interact_menu_more__ACE_Tags = false;
ace_interact_menu_more__ACE_TeamManagement = false;
ace_interact_menu_more__ace_zeus_create = false;
ace_interact_menu_more__ace_zeus_delete = false;
ace_interact_menu_more__acex_sitting_Stand = false;
ace_interact_menu_more__KAT_Equipment = false;
ace_interact_menu_more__Medical = false;
ace_interact_menu_more__TFAR_Radio = false;
ace_interact_menu_more__Third_SelfActions_Insignias = false;
ace_interact_menu_more__vtx_detachHook = false;

// ACE Interaction Menu (Self) - Move to Root
ace_interact_menu_moveToRoot__ACE_Equipment__ace_atragmx_open = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_attach_Attach = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_attach_Detach = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ACE_CheckDogtags = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ACE_Chemlights = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_dagr_menu = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_dagr_menu__ace_dagr_toggle = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_flags = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_flags__ace_flags_furlFlag = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_goggles_wipeGlasses = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_gunbag_actions = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_gunbag_actions__ace_gunbag_status = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_gunbag_actions__ace_gunbag_weaponOff = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_gunbag_actions__ace_gunbag_weaponSwap = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_gunbag_actions__ace_gunbag_weaponTo = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_huntir_open = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_interaction_weaponAttachments = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_kestrel4500_open = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_kestrel4500_open__ace_kestrel4500_hide = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_kestrel4500_open__ace_kestrel4500_show = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_marker_flags = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_microdagr_configure = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_microdagr_configure__ace_microdagr_close = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_microdagr_configure__ace_microdagr_show = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_minedetector_metalDetector = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_minedetector_metalDetector__ace_minedetector_activate = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_minedetector_metalDetector__ace_minedetector_connectHeadphones = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_minedetector_metalDetector__ace_minedetector_deactivate = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_minedetector_metalDetector__ace_minedetector_disconnectHeadphones = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_mk6mortar_rangetable = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_overheating_CheckTemperature = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_overheating_CheckTemperatureSpareBarrels = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_overheating_CoolWeaponWithItem = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_overheating_SwapBarrel = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_overheating_UnJam = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ACE_PutInEarplugs = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ACE_PutOnEHP = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_rangecard_open = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_rangecard_open__ace_rangecard_makeCopy = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_rangecard_open__ace_rangecard_openCopy = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_reload_checkAmmo = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ACE_RemoveEarplugs = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ACE_RemoveEHP = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_scopes_adjustZero = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_scopes_resetZero = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_spottingscope_place = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ACE_TacticalLadders = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_trenches = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_trenches__ace_trenches_digEnvelopeBig = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_trenches__ace_trenches_digEnvelopeSmall = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_trenches__grad_trenches_digEnvelopeGiant = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_trenches__grad_trenches_digEnvelopeLongNameEmplacment = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_trenches__grad_trenches_digEnvelopeShort = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_trenches__grad_trenches_digEnvelopeVehicle = false;
ace_interact_menu_moveToRoot__ACE_Equipment__ace_tripod_place = false;
ace_interact_menu_moveToRoot__ACE_Equipment__bocr_main_cutLoweringLine = false;
ace_interact_menu_moveToRoot__ACE_Equipment__bocr_main_lower = false;
ace_interact_menu_moveToRoot__ACE_Equipment__bocr_main_onBack = false;
ace_interact_menu_moveToRoot__ACE_Equipment__bocr_main_onChest = false;
ace_interact_menu_moveToRoot__ACE_Equipment__bocr_main_swap = false;
ace_interact_menu_moveToRoot__ACE_Equipment__uh60_jvmf_tablet = false;
ace_interact_menu_moveToRoot__ACE_Equipment__vtx_stretcher_1 = false;
ace_interact_menu_moveToRoot__ACE_Explosives__ACE_Cellphone = false;
ace_interact_menu_moveToRoot__ACE_Explosives__ACE_Place = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Advance = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_CeaseFire = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Cover = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Engage = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Follow = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Forward = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Freeze = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Go = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Hold = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Point = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Regroup = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Stop = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Up = false;
ace_interact_menu_moveToRoot__ace_gestures__ace_gestures_Warning = false;
ace_interact_menu_moveToRoot__ACE_MapTools__ACE_MapToolsAlign = false;
ace_interact_menu_moveToRoot__ACE_MapTools__ACE_MapToolsAlign__ACE_MapToolsAlignCompass = false;
ace_interact_menu_moveToRoot__ACE_MapTools__ACE_MapToolsAlign__ACE_MapToolsAlignNorth = false;
ace_interact_menu_moveToRoot__ACE_MapTools__ACE_MapToolsAlign__ACE_MapToolsAlignToPlottingBoard = false;
ace_interact_menu_moveToRoot__ACE_MapTools__ACE_MapToolsAlign__ACE_MapToolsAlignToPlottingBoardAcrylic = false;
ace_interact_menu_moveToRoot__ACE_MapTools__ACE_MapToolsAlign__ACE_MapToolsAlignToPlottingBoardRuler = false;
ace_interact_menu_moveToRoot__ACE_MapTools__ACE_MapToolsHide = false;
ace_interact_menu_moveToRoot__ACE_MapTools__ACE_MapToolsShowNormal = false;
ace_interact_menu_moveToRoot__ACE_MapTools__ACE_MapToolsShowSmall = false;
ace_interact_menu_moveToRoot__ACE_Medical__ACE_ArmLeft = false;
ace_interact_menu_moveToRoot__ACE_Medical__ACE_ArmRight = false;
ace_interact_menu_moveToRoot__ACE_Medical__ACE_Head = false;
ace_interact_menu_moveToRoot__ACE_Medical__ACE_LegLeft = false;
ace_interact_menu_moveToRoot__ACE_Medical__ACE_LegRight = false;
ace_interact_menu_moveToRoot__ACE_Medical__ACE_Torso = false;
ace_interact_menu_moveToRoot__ACE_Medical__ACE_Torso__TriageCard = false;
ace_interact_menu_moveToRoot__ACE_PlottingBoardHide__ACE_PlottingBoardAlign = false;
ace_interact_menu_moveToRoot__ACE_PlottingBoardHide__ACE_PlottingBoardAlign__ACE_PlottingBoardAlignAcrylic = false;
ace_interact_menu_moveToRoot__ACE_PlottingBoardHide__ACE_PlottingBoardAlign__ACE_PlottingBoardAlignAcrylic__ACE_PlottingBoardAlignAcrylicMaptool = false;
ace_interact_menu_moveToRoot__ACE_PlottingBoardHide__ACE_PlottingBoardAlign__ACE_PlottingBoardAlignAcrylic__ACE_PlottingBoardAlignAcrylicUp = false;
ace_interact_menu_moveToRoot__ACE_PlottingBoardHide__ACE_PlottingBoardAlign__ACE_PlottingBoardAlignBoard = false;
ace_interact_menu_moveToRoot__ACE_PlottingBoardHide__ACE_PlottingBoardAlign__ACE_PlottingBoardAlignBoard__ACE_PlottingBoardAlignBoardMaptool = false;
ace_interact_menu_moveToRoot__ACE_PlottingBoardHide__ACE_PlottingBoardAlign__ACE_PlottingBoardAlignBoard__ACE_PlottingBoardAlignBoardUp = false;
ace_interact_menu_moveToRoot__ACE_PlottingBoardHide__ACE_PlottingBoardAlign__ACE_PlottingBoardAlignRuler = false;
ace_interact_menu_moveToRoot__ACE_PlottingBoardHide__ACE_PlottingBoardAlign__ACE_PlottingBoardAlignRuler__ACE_PlottingBoardAlignRulerMaptool = false;
ace_interact_menu_moveToRoot__ACE_PlottingBoardHide__ACE_PlottingBoardAlign__ACE_PlottingBoardAlignRuler__ACE_PlottingBoardAlignRulerUp = false;
ace_interact_menu_moveToRoot__ACE_PlottingBoardHide__ACE_PlottingBoardRulerHide = false;
ace_interact_menu_moveToRoot__ACE_PlottingBoardHide__ACE_PlottingBoardRulerShow = false;
ace_interact_menu_moveToRoot__ACE_PlottingBoardHide__ACE_PlottingBoardWipe = false;
ace_interact_menu_moveToRoot__ACE_TeamManagement__ACE_BecomeLeader = false;
ace_interact_menu_moveToRoot__ACE_TeamManagement__ACE_JoinTeamBlue = false;
ace_interact_menu_moveToRoot__ACE_TeamManagement__ACE_JoinTeamGreen = false;
ace_interact_menu_moveToRoot__ACE_TeamManagement__ACE_JoinTeamMain = false;
ace_interact_menu_moveToRoot__ACE_TeamManagement__ACE_JoinTeamRed = false;
ace_interact_menu_moveToRoot__ACE_TeamManagement__ACE_JoinTeamYellow = false;
ace_interact_menu_moveToRoot__ACE_TeamManagement__ACE_LeaveGroup = false;
ace_interact_menu_moveToRoot__ACE_TeamManagement__ACE_remoteTeamManagement = false;
ace_interact_menu_moveToRoot__ACE_TeamManagement__ACE_RenameGroup = false;
ace_interact_menu_moveToRoot__ACE_TeamManagement__diwako_dui_buddy_buddy_action_team_remove = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftArm = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftArm__Doctor = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftArm__Doctor_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftArm__Kat = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftArm__Kat_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftArm__Medic = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftArm__Medic_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftArm__RedCross = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftArm__RedCross_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftLeg = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftLeg__Doctor = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftLeg__Doctor_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftLeg__Kat = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftLeg__Kat_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftLeg__Medic = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftLeg__Medic_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftLeg__RedCross = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__LeftLeg__RedCross_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightArm = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightArm__Doctor = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightArm__Doctor_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightArm__Kat = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightArm__Kat_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightArm__Medic = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightArm__Medic_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightArm__RedCross = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightArm__RedCross_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightLeg = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightLeg__Doctor = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightLeg__Doctor_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightLeg__Kat = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightLeg__Kat_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightLeg__Medic = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightLeg__Medic_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightLeg__RedCross = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__RightLeg__RedCross_NVG = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__UnSlingLeftArm = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__UnSlingLeftLeg = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__UnSlingRightArm = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Armband__UnSlingRightLeg = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Attach_PersonalOxygen = false;
ace_interact_menu_moveToRoot__KAT_Equipment__BubbleWrapPopping = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Check_PersonalOxygen = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Detach_PersonalOxygen = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AED_X_Interactions = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AED_X_Interactions__KAT_AED_X_addSound = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AED_X_Interactions__KAT_AED_X_removeSound = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AED_X_Interactions__KAT_AED_X_ViewMonitor = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Item = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Item__AFAKInfo = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Item__Slot1 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Item__Slot2 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Item__Slot3 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Item__Slot4 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Item__Slot5 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Item__Slot6 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Mag = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Mag__AFAKInfo = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Mag__Slot1 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Mag__Slot1_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Mag__Slot2 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Mag__Slot2_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Mag__Slot3 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Mag__Slot3_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Mag__Slot4 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Mag__Slot4_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Mag__Slot5 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Mag__Slot5_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Mag__Slot6 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_AFAK_Mag__Slot6_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_ChangeGasMaskFilter = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_CheckGasMaskDur = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_CheckHandWarmersSelf = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_ChemicalDetector = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_ChemicalDetector__KAT_ChemicalDetector_Enable = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_ChemicalDetector__KAT_ChemicalDetector_SoundOff = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_ChemicalDetector__KAT_ChemicalDetector_SoundOn = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_DeployStretcher = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Item = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Item__IFAKInfo = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Item__Slot1 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Item__Slot2 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Item__Slot3 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Item__Slot4 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Mag = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Mag__IFAKInfo = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Mag__Slot1 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Mag__Slot1_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Mag__Slot2 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Mag__Slot2_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Mag__Slot3 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Mag__Slot3_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Mag__Slot4 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_IFAK_Mag__Slot4_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Item = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Item__MFAKInfo = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Item__Slot1 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Item__Slot2 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Item__Slot3 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Item__Slot4 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Item__Slot5 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Item__Slot6 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Item__Slot7 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Item__Slot8 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__MFAKInfo = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot1 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot1_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot2 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot2_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot3 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot3_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot4 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot4_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot5 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot5_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot6 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot6_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot7 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot7_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot8 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_MFAK_Mag__Slot8_Repack = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_placeAED = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_placeAEDX = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_PutOnGasMask = false;
ace_interact_menu_moveToRoot__KAT_Equipment__KAT_TakeOffGasMask = false;
ace_interact_menu_moveToRoot__KAT_Equipment__openCrossPanel = false;
ace_interact_menu_moveToRoot__KAT_Equipment__PulseOximeter_addSound = false;
ace_interact_menu_moveToRoot__KAT_Equipment__PulseOximeter_removeSound = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Refill_OxygenTank_150_Facility = false;
ace_interact_menu_moveToRoot__KAT_Equipment__Refill_OxygenTank_300_Facility = false;
ace_interact_menu_moveToRoot__KAT_Equipment__SetPreferred_OxygenTank_150 = false;
ace_interact_menu_moveToRoot__KAT_Equipment__SetPreferred_OxygenTank_300 = false;
ace_interact_menu_moveToRoot__Medical__ACE_Head = false;
ace_interact_menu_moveToRoot__Medical__ACE_Head__CheckBloodPressure = false;
ace_interact_menu_moveToRoot__Third_SelfActions_Insignias__Third_SelfActions_Insignias_1P_Group = false;
ace_interact_menu_moveToRoot__Third_SelfActions_Insignias__Third_SelfActions_Insignias_1P_Group__Third_SelfActions_Insignias_Normal = false;
ace_interact_menu_moveToRoot__Third_SelfActions_Insignias__Third_SelfActions_Insignias_1P_Group__Third_SelfActions_Insignias_Normal__Third_SelfActions_Insignias_Ghosts = false;
ace_interact_menu_moveToRoot__Third_SelfActions_Insignias__Third_SelfActions_Insignias_1P_Group__Third_SelfActions_Insignias_Normal__Third_SelfActions_Insignias_Phoenix = false;
ace_interact_menu_moveToRoot__Third_SelfActions_Insignias__Third_SelfActions_Insignias_1P_Group__Third_SelfActions_Insignias_Normal__Third_SelfActions_Insignias_Reapers = false;
ace_interact_menu_moveToRoot__Third_SelfActions_Insignias__Third_SelfActions_Insignias_1P_Group__Third_SelfActions_Insignias_Normal__Third_SelfActions_Insignias_Scorpions = false;
ace_interact_menu_moveToRoot__Third_SelfActions_Insignias__Third_SelfActions_Insignias_1P_Group__Third_SelfActions_Insignias_Normal__Third_SelfActions_Insignias_Spartans = false;
ace_interact_menu_moveToRoot__Third_SelfActions_Insignias__Third_SelfActions_Insignias_1P_Group__Third_SelfActions_Insignias_Normal__Third_SelfActions_Insignias_Widowmakers = false;
ace_interact_menu_moveToRoot__Third_SelfActions_Insignias__Third_SelfActions_Insignias_1P_Group__Third_SelfActions_Insignias_Ranger = false;
ace_interact_menu_moveToRoot__Third_SelfActions_Insignias__Third_SelfActions_Insignias_1P_Group__Third_SelfActions_Insignias_Ranger__Third_SelfActions_Insignias_Ghosts_Ranger = false;
ace_interact_menu_moveToRoot__Third_SelfActions_Insignias__Third_SelfActions_Insignias_1P_Group__Third_SelfActions_Insignias_Ranger__Third_SelfActions_Insignias_Phoenix_Ranger = false;
ace_interact_menu_moveToRoot__Third_SelfActions_Insignias__Third_SelfActions_Insignias_1P_Group__Third_SelfActions_Insignias_Ranger__Third_SelfActions_Insignias_Reapers_Ranger = false;
ace_interact_menu_moveToRoot__Third_SelfActions_Insignias__Third_SelfActions_Insignias_1P_Group__Third_SelfActions_Insignias_Ranger__Third_SelfActions_Insignias_Scorpions_Ranger = false;
ace_interact_menu_moveToRoot__Third_SelfActions_Insignias__Third_SelfActions_Insignias_1P_Group__Third_SelfActions_Insignias_Ranger__Third_SelfActions_Insignias_Spartans_Ranger = false;
ace_interact_menu_moveToRoot__Third_SelfActions_Insignias__Third_SelfActions_Insignias_1P_Group__Third_SelfActions_Insignias_Ranger__Third_SelfActions_Insignias_Widowmakers_Ranger = false;
ace_interact_menu_moveToRoot__Third_SelfActions_Insignias__Third_SelfActions_Insignias_2P_Group = false;
ace_interact_menu_moveToRoot__Third_SelfActions_Insignias__Third_SelfActions_Insignias_2P_Group__Third_SelfActions_Insignias_Normal = false;
ace_interact_menu_moveToRoot__Third_SelfActions_Insignias__Third_SelfActions_Insignias_2P_Group__Third_SelfActions_Insignias_Normal__Third_SelfActions_Insignias_Griffins = false;
ace_interact_menu_moveToRoot__Third_SelfActions_Insignias__Third_SelfActions_Insignias_2P_Group__Third_SelfActions_Insignias_Normal__Third_SelfActions_Insignias_Warlocks = false;
ace_interact_menu_moveToRoot__Third_SelfActions_Insignias__Third_SelfActions_Insignias_2P_Group__Third_SelfActions_Insignias_Normal__Third_SelfActions_Insignias_Wizards = false;
ace_interact_menu_moveToRoot__Third_SelfActions_Insignias__Third_SelfActions_Insignias_2P_Group__Third_SelfActions_Insignias_Ranger = false;
ace_interact_menu_moveToRoot__Third_SelfActions_Insignias__Third_SelfActions_Insignias_2P_Group__Third_SelfActions_Insignias_Ranger__Third_SelfActions_Insignias_Griffins_Ranger = false;
ace_interact_menu_moveToRoot__Third_SelfActions_Insignias__Third_SelfActions_Insignias_2P_Group__Third_SelfActions_Insignias_Ranger__Third_SelfActions_Insignias_Warlocks_Ranger = false;
ace_interact_menu_moveToRoot__Third_SelfActions_Insignias__Third_SelfActions_Insignias_2P_Group__Third_SelfActions_Insignias_Ranger__Third_SelfActions_Insignias_Wizards_Ranger = false;
ace_interact_menu_moveToRoot__Third_SelfActions_Insignias__Third_SelfActions_Insignias_3CAB_Group = false;
ace_interact_menu_moveToRoot__Third_SelfActions_Insignias__Third_SelfActions_Insignias_3CAB_Group__Third_SelfActions_Insignias_Normal = false;
ace_interact_menu_moveToRoot__Third_SelfActions_Insignias__Third_SelfActions_Insignias_3CAB_Group__Third_SelfActions_Insignias_Normal__Third_SelfActions_Insignias_3Cab = false;
ace_interact_menu_moveToRoot__Third_SelfActions_Insignias__Third_SelfActions_Insignias_3CAB_Group__Third_SelfActions_Insignias_Normal__Third_SelfActions_Insignias_Lifeline = false;
ace_interact_menu_moveToRoot__Third_SelfActions_Insignias__Third_SelfActions_Insignias_3CAB_Group__Third_SelfActions_Insignias_Normal__Third_SelfActions_Insignias_Stalker = false;
ace_interact_menu_moveToRoot__Third_SelfActions_Insignias__Third_SelfActions_Insignias_3CAB_Group__Third_SelfActions_Insignias_Normal__Third_SelfActions_Insignias_Stallion = false;
ace_interact_menu_moveToRoot__Third_SelfActions_Insignias__Third_SelfActions_Insignias_3CAB_Group__Third_SelfActions_Insignias_Normal__Third_SelfActions_Insignias_Voodoo = false;
ace_interact_menu_moveToRoot__Third_SelfActions_Insignias__Third_SelfActions_Insignias_3CAB_Group__Third_SelfActions_Insignias_Ranger = false;
ace_interact_menu_moveToRoot__Third_SelfActions_Insignias__Third_SelfActions_Insignias_3CAB_Group__Third_SelfActions_Insignias_Ranger__Third_SelfActions_Insignias_3Cab_Ranger = false;
ace_interact_menu_moveToRoot__Third_SelfActions_Insignias__Third_SelfActions_Insignias_3CAB_Group__Third_SelfActions_Insignias_Ranger__Third_SelfActions_Insignias_Lifeline_Ranger = false;
ace_interact_menu_moveToRoot__Third_SelfActions_Insignias__Third_SelfActions_Insignias_3CAB_Group__Third_SelfActions_Insignias_Ranger__Third_SelfActions_Insignias_Stalker_Ranger = false;
ace_interact_menu_moveToRoot__Third_SelfActions_Insignias__Third_SelfActions_Insignias_3CAB_Group__Third_SelfActions_Insignias_Ranger__Third_SelfActions_Insignias_Stallion_Ranger = false;
ace_interact_menu_moveToRoot__Third_SelfActions_Insignias__Third_SelfActions_Insignias_3CAB_Group__Third_SelfActions_Insignias_Ranger__Third_SelfActions_Insignias_Voodoo_Ranger = false;
ace_interact_menu_moveToRoot__Third_SelfActions_Insignias__Third_SelfActions_Insignias_Reserves_Group = false;
ace_interact_menu_moveToRoot__Third_SelfActions_Insignias__Third_SelfActions_Insignias_Reserves_Group__Third_SelfActions_Insignias_Reserves = false;
ace_interact_menu_moveToRoot__Third_SelfActions_Insignias__Third_SelfActions_Insignias_Reserves_Group__Third_SelfActions_Insignias_Reserves_Ranger = false;
ace_interact_menu_moveToRoot__Third_SelfActions_Insignias__Third_SelfActions_Insignias_WarEagles_Group = false;
ace_interact_menu_moveToRoot__Third_SelfActions_Insignias__Third_SelfActions_Insignias_WarEagles_Group__Third_SelfActions_Insignias_WarEagles = false;
ace_interact_menu_moveToRoot__Third_SelfActions_Insignias__Third_SelfActions_Insignias_WarEagles_Group__Third_SelfActions_Insignias_WarEagles_Ranger = false;

// ACE Kill Tracker
force ace_killtracker_showCrewKills = true;
force ace_killtracker_showMedicalWounds = 2;
force ace_killtracker_trackAI = true;

// ACE Logistics
ace_cargo_carryAfterUnload = true;
ace_cargo_checkSizeInteraction = false;
force force ace_cargo_enable = true;
force ace_cargo_enableDeploy = true;
ace_cargo_enableRename = true;
force force ace_cargo_loadTimeCoefficient = 5;
ace_cargo_openAfterUnload = 0;
force force ace_cargo_paradropTimeCoefficent = 0.5;
force force ace_rearm_distance = 20;
force ace_rearm_enabled = true;
force force ace_rearm_level = 0;
force force ace_rearm_supply = 0;
force ace_refuel_cargoRate = 10;
force ace_refuel_enabled = true;
force force ace_refuel_hoseLength = 30;
force ace_refuel_progressDuration = 2;
force force ace_refuel_rate = 1;
force ace_towing_addRopeToVehicleInventory = true;

// ACE Magazine Repack
ace_magazinerepack_repackAnimation = true;
ace_magazinerepack_repackLoadedMagazines = true;
force force ace_magazinerepack_timePerAmmo = 1;
force force ace_magazinerepack_timePerBeltLink = 8;
force force ace_magazinerepack_timePerMagazine = 2;

// ACE Map
force force ace_map_BFT_Enabled = false;
force force ace_map_BFT_HideAiGroups = true;
force force ace_map_BFT_Interval = 1;
force force ace_map_BFT_ShowPlayerNames = false;
force force ace_map_DefaultChannel = -1;
force force ace_map_mapGlow = true;
force force ace_map_mapIllumination = true;
force force ace_map_mapLimitZoom = false;
force force ace_map_mapShake = true;
force force ace_map_mapShowCursorCoordinates = false;
force force ace_markers_moveRestriction = 0;
ace_markers_timestampEnabled = true;
ace_markers_timestampFormat = "HH:MM";
ace_markers_timestampHourFormat = 24;
force ace_markers_timestampTimezone = 0;
ace_markers_TimestampUTCMinutesOffset = 0;
force ace_markers_timestampUTCOffset = 0;

// ACE Map Gestures
ace_map_gestures_allowCurator = true;
ace_map_gestures_allowSpectator = true;
ace_map_gestures_briefingMode = 0;
force force ace_map_gestures_defaultColor = [1,0.88,0,0.7];
force force ace_map_gestures_defaultLeadColor = [1,0.88,0,0.95];
force force ace_map_gestures_enabled = true;
force force ace_map_gestures_interval = 0.03;
force force ace_map_gestures_maxRange = 7;
force ace_map_gestures_maxRangeCamera = 14;
force force ace_map_gestures_nameTextColor = [0.2,0.2,0.2,0.3];
force ace_map_gestures_onlyShowFriendlys = false;

// ACE Map Tools
force force ace_maptools_drawStraightLines = true;
ace_maptools_plottingBoardAllowChannelDrawing = 1;
force force ace_maptools_rotateModifierKey = 1;

// ACE Medical
force ace_medical_ai_enabledFor = 2;
force ace_medical_ai_requireItems = 0;
force force ace_medical_AIDamageThreshold = 0.7;
force force ace_medical_bleedingCoefficient = 0.2;
force force ace_medical_blood_bloodLifetime = 300;
force force ace_medical_blood_enabledFor = 1;
force force ace_medical_blood_maxBloodObjects = 100;
force ace_medical_deathChance = 0.250032;
force ace_medical_dropWeaponUnconsciousChance = 0;
force ace_medical_enableVehicleCrashes = true;
force ace_medical_engine_damagePassThroughEffect = 1;
force force ace_medical_fatalDamageSource = 2;
force force ace_medical_fractureChance = 0.1;
force force ace_medical_fractures = 1;
force force ace_medical_ivFlowRate = 1;
force ace_medical_limbDamageThreshold = 5;
force force ace_medical_limping = 1;
force force ace_medical_painCoefficient = 0.7;
force force ace_medical_painUnconsciousChance = 0.1;
force ace_medical_painUnconsciousThreshold = 0.5;
force force ace_medical_playerDamageThreshold = 5;
force force ace_medical_spontaneousWakeUpChance = 0.3;
force force ace_medical_spontaneousWakeUpEpinephrineBoost = 30;
force ace_medical_statemachine_AIUnconsciousness = false;
force ace_medical_statemachine_cardiacArrestBleedoutEnabled = true;
force force ace_medical_statemachine_cardiacArrestTime = 600;
force ace_medical_statemachine_fatalInjuriesAI = 0;
force force ace_medical_statemachine_fatalInjuriesPlayer = 2;
force ace_medical_useLimbDamage = 0;
force ace_medical_vitals_simulateSpO2 = true;

// ACE Medical Interface
force force ace_medical_feedback_bloodVolumeEffectType = 0;
ace_medical_feedback_enableHUDIndicators = true;
force force ace_medical_feedback_painEffectType = 2;
ace_medical_gui_bloodLossColor_0 = [1,1,1,1];
ace_medical_gui_bloodLossColor_1 = [1,0.94,0.48,1];
ace_medical_gui_bloodLossColor_2 = [1,0.87,0.25,1];
ace_medical_gui_bloodLossColor_3 = [1,0.79,0.17,1];
ace_medical_gui_bloodLossColor_4 = [1,0.71,0.11,1];
ace_medical_gui_bloodLossColor_5 = [1,0.62,0.05,1];
ace_medical_gui_bloodLossColor_6 = [1,0.53,0.01,1];
ace_medical_gui_bloodLossColor_7 = [1,0.42,0,1];
ace_medical_gui_bloodLossColor_8 = [1,0.29,0,1];
ace_medical_gui_bloodLossColor_9 = [1,0,0,1];
ace_medical_gui_bodyPartOutlineColor = [1,1,1,1];
ace_medical_gui_damageColor_0 = [1,1,1,1];
ace_medical_gui_damageColor_1 = [0.52,0.73,1,1];
ace_medical_gui_damageColor_2 = [0.38,0.68,1,1];
ace_medical_gui_damageColor_3 = [0.37,0.6,1,1];
ace_medical_gui_damageColor_4 = [0.35,0.53,1,1];
ace_medical_gui_damageColor_5 = [0.33,0.45,1,1];
ace_medical_gui_damageColor_6 = [0.3,0.37,1,1];
ace_medical_gui_damageColor_7 = [0.25,0.29,1,1];
ace_medical_gui_damageColor_8 = [0.18,0.18,1,1];
ace_medical_gui_damageColor_9 = [0,0,1,1];
ace_medical_gui_enableActions = 0;
ace_medical_gui_enableMedicalMenu = 1;
ace_medical_gui_enableSelfActions = true;
ace_medical_gui_interactionMenuShowTriage = 1;
force ace_medical_gui_maxDistance = 3;
ace_medical_gui_openAfterTreatment = true;
ace_medical_gui_peekMedicalInfoReleaseDelay = 1;
ace_medical_gui_peekMedicalOnHit = false;
ace_medical_gui_peekMedicalOnHitDuration = 1;
force ace_medical_gui_showBleeding = 2;
force ace_medical_gui_showBloodlossEntry = true;
force ace_medical_gui_showDamageEntry = false;
ace_medical_gui_tourniquetWarning = false;

// ACE Medical Treatment
force force ace_medical_treatment_advancedBandages = 2;
force ace_medical_treatment_advancedDiagnose = 1;
force force ace_medical_treatment_advancedMedication = true;
force ace_medical_treatment_allowBodyBagUnconscious = false;
force ace_medical_treatment_allowGraveDigging = 1;
force force ace_medical_treatment_allowLitterCreation = true;
force force ace_medical_treatment_allowSelfIV = 1;
force force ace_medical_treatment_allowSelfPAK = 1;
force force ace_medical_treatment_allowSelfStitch = 1;
force force ace_medical_treatment_allowSharedEquipment = 3;
force ace_medical_treatment_bandageEffectiveness = 1;
ace_medical_treatment_bandageRollover = true;
force ace_medical_treatment_clearTrauma = 1;
force force ace_medical_treatment_consumePAK = 0;
force force ace_medical_treatment_consumeSurgicalKit = 0;
force force ace_medical_treatment_convertItems = 0;
force ace_medical_treatment_cprSuccessChanceMax = 0.35;
force ace_medical_treatment_cprSuccessChanceMin = 0.35;
force ace_medical_treatment_graveDiggingMarker = true;
force force ace_medical_treatment_holsterRequired = 0;
force force ace_medical_treatment_litterCleanupDelay = 300;
force ace_medical_treatment_locationAdenosine = 0;
force force ace_medical_treatment_locationEpinephrine = 0;
force ace_medical_treatment_locationIV = 0;
force ace_medical_treatment_locationMorphine = 0;
force force ace_medical_treatment_locationPAK = 0;
force force ace_medical_treatment_locationsBoostTraining = true;
force ace_medical_treatment_locationSplint = 0;
force force ace_medical_treatment_locationSurgicalKit = 0;
force force ace_medical_treatment_maxLitterObjects = 100;
force ace_medical_treatment_medicAdenosine = 1;
force force ace_medical_treatment_medicEpinephrine = 0;
force force ace_medical_treatment_medicIV = 1;
force ace_medical_treatment_medicMorphine = 0;
force force ace_medical_treatment_medicPAK = 2;
force ace_medical_treatment_medicSplint = 0;
force force ace_medical_treatment_medicSurgicalKit = 2;
force ace_medical_treatment_numericalPulse = 1;
force force ace_medical_treatment_timeCoefficientPAK = 0.6;
force ace_medical_treatment_treatmentTimeAutoinjector = 2;
force ace_medical_treatment_treatmentTimeBodyBag = 15;
ace_medical_treatment_treatmentTimeCoeffZeus = 1;
force ace_medical_treatment_treatmentTimeCPR = 10;
force ace_medical_treatment_treatmentTimeGrave = 30;
force ace_medical_treatment_treatmentTimeIV = 8;
force ace_medical_treatment_treatmentTimeSplint = 7;
force ace_medical_treatment_treatmentTimeTourniquet = 4;
force ace_medical_treatment_treatmentTimeTrainedAutoinjector = 2.005;
force ace_medical_treatment_treatmentTimeTrainedIV = 8;
force ace_medical_treatment_treatmentTimeTrainedSplint = 7;
force ace_medical_treatment_treatmentTimeTrainedTourniquet = 4.005;
force force ace_medical_treatment_woundReopenChance = 0.5;
force force ace_medical_treatment_woundStitchTime = 2;

// ACE Name Tags
force ace_nametags_ambientBrightnessAffectViewDist = 1;
ace_nametags_defaultNametagColor = [0.77,0.51,0.08,1];
ace_nametags_nametagColorBlue = [0.67,0.67,1,1];
ace_nametags_nametagColorGreen = [0.67,1,0.67,1];
ace_nametags_nametagColorMain = [1,1,1,1];
ace_nametags_nametagColorRed = [1,0.67,0.67,1];
ace_nametags_nametagColorYellow = [1,1,0.67,1];
force ace_nametags_playerNamesMaxAlpha = 0.8;
force ace_nametags_playerNamesViewDistance = 5;
force ace_nametags_showCursorTagForVehicles = false;
force force ace_nametags_showNamesForAI = false;
force force ace_nametags_showPlayerNames = 0;
ace_nametags_showPlayerRanks = true;
ace_nametags_showSoundWaves = 1;
ace_nametags_showVehicleCrewInfo = true;
ace_nametags_tagSize = 2;

// ACE Nightvision
force force ace_nightvision_aimDownSightsBlur = 0.104723;
force force ace_nightvision_disableNVGsWithSights = false;
force ace_nightvision_effectScaling = 0;
force ace_nightvision_fogScaling = 0;
force ace_nightvision_noiseScaling = 0;
force force ace_nightvision_shutterEffects = true;

// ACE Overheating
force force ace_overheating_cookoffCoef = 1;
force force ace_overheating_coolingCoef = 1;
force force ace_overheating_displayTextOnJam = true;
force force ace_overheating_enabled = false;
force force ace_overheating_heatCoef = 1;
force force ace_overheating_jamChanceCoef = 1;
force force ace_overheating_overheatingDispersion = true;
force force ace_overheating_overheatingRateOfFire = true;
force force ace_overheating_particleEffectsAndDispersionDistance = 3000;
force force ace_overheating_showParticleEffects = true;
force force ace_overheating_showParticleEffectsForEveryone = false;
force force ace_overheating_suppressorCoef = 1;
force force ace_overheating_unJamFailChance = 0.1;
force force ace_overheating_unJamOnreload = true;
force force ace_overheating_unJamOnSwapBarrel = true;

// ACE Pointing
force force ace_finger_enabled = true;
force force ace_finger_indicatorColor = [0.83,0.68,0.21,0.75];
force force ace_finger_indicatorForSelf = true;
force force ace_finger_maxRange = 10.4167;
force ace_finger_proximityScaling = false;
force ace_finger_sizeCoef = 1;

// ACE Pylons
force force ace_pylons_enabledForZeus = true;
force force ace_pylons_enabledFromAmmoTrucks = true;
force force ace_pylons_rearmNewPylons = true;
force force ace_pylons_requireEngineer = false;
force force ace_pylons_requireToolkit = false;
force force ace_pylons_searchDistance = 15;
force force ace_pylons_timePerPylon = 5;

// ACE Quick Mount
force ace_quickmount_distance = 3;
force force ace_quickmount_enabled = true;
ace_quickmount_enableMenu = 3;
ace_quickmount_priority = 0;
force ace_quickmount_speed = 18;

// ACE Repair
force force ace_repair_addSpareParts = true;
force force ace_repair_autoShutOffEngineWhenStartingRepair = false;
force force ace_repair_consumeItem_toolKit = 0;
force force ace_repair_displayTextOnRepair = true;
force ace_repair_enabled = true;
force force ace_repair_engineerSetting_fullRepair = 2;
force force ace_repair_engineerSetting_repair = 1;
force force ace_repair_engineerSetting_wheel = 0;
force force ace_repair_fullRepairLocation = 2;
force ace_repair_fullRepairRequiredItems = ["ace_repair_anyToolKit"];
force ace_repair_locationsBoostTraining = false;
force ace_repair_miscRepairRequiredItems = ["ace_repair_anyToolKit"];
force ace_repair_miscRepairTime = 15;
force ace_repair_patchWheelEnabled = 0;
force ace_repair_patchWheelLocation = ["ground","vehicle"];
force ace_repair_patchWheelMaximumRepair = 0.3;
force ace_repair_patchWheelRequiredItems = ["ace_repair_anyToolKit"];
force ace_repair_patchWheelTime = 5;
force force ace_repair_repairDamageThreshold = 0.6;
force force ace_repair_repairDamageThreshold_engineer = 0.4;
force ace_repair_timeCoefficientFullRepair = 1.5;
force ace_repair_wheelChangeTime = 10;
force force ace_repair_wheelRepairRequiredItems = [];

// ACE Respawn
force force ace_respawn_removeDeadBodiesDisconnected = true;
force force ace_respawn_savePreDeathGear = true;

// ACE Scopes
force force ace_scopes_correctZeroing = true;
force force ace_scopes_deduceBarometricPressureFromTerrainAltitude = true;
force force ace_scopes_defaultZeroRange = 100;
force force ace_scopes_enabled = true;
force force ace_scopes_forceUseOfAdjustmentTurrets = true;
ace_scopes_inScopeAdjustment = false;
force force ace_scopes_overwriteZeroRange = true;
force force ace_scopes_simplifiedZeroing = false;
ace_scopes_useLegacyUI = true;
force force ace_scopes_zeroReferenceBarometricPressure = 1013.25;
force force ace_scopes_zeroReferenceHumidity = 0;
force force ace_scopes_zeroReferenceTemperature = 15;

// ACE Sitting
force acex_sitting_enable = true;

// ACE Spectator
force ace_spectator_enableAI = false;
ace_spectator_maxFollowDistance = 5;
force ace_spectator_restrictModes = 0;
force ace_spectator_restrictVisions = 0;

// ACE Switch Units
force ace_switchunits_enableSafeZone = true;
force ace_switchunits_enableSwitchUnits = false;
force ace_switchunits_safeZoneRadius = 100;
force ace_switchunits_switchToCivilian = false;
force ace_switchunits_switchToEast = false;
force ace_switchunits_switchToIndependent = false;
force ace_switchunits_switchToWest = false;

// ACE Trenches
force ace_trenches_bigEnvelopeDigDuration = 25;
force ace_trenches_bigEnvelopeRemoveDuration = 15;
force ace_trenches_smallEnvelopeDigDuration = 20;
force ace_trenches_smallEnvelopeRemoveDuration = 12;

// ACE Uncategorized
force ace_fastroping_autoAddFRIES = false;
force ace_fastroping_requireRopeItems = false;
ace_flags_enableCarrying = true;
ace_flags_enablePlacing = true;
force ace_gunbag_swapGunbagEnabled = true;
force force ace_hitreactions_minDamageToTrigger = 0.05;
force ace_hitreactions_weaponDropChanceArmHitAI = 0;
force ace_hitreactions_weaponDropChanceArmHitPlayer = 0;
force force ace_inventory_inventoryDisplaySize = 0;
force force ace_laser_dispersionCount = 2;
force ace_laser_showLaserOnMap = 1;
force ace_marker_flags_placeAnywhere = false;
force force ace_microdagr_mapDataAvailable = 2;
force ace_microdagr_waypointPrecision = 3;
force ace_noradio_enabled = true;
force force ace_optionsmenu_showNewsOnMainMenu = true;
force ace_overpressure_backblastDistanceCoefficient = 1;
force ace_overpressure_overpressureDistanceCoefficient = 1;
force ace_parachute_failureChance = 0;
ace_parachute_hideAltimeter = false;
ace_tagging_quickTag = 1;

// ACE User Interface
force force ace_ui_allowSelectiveUI = true;
force force ace_ui_ammoCount = false;
force force ace_ui_ammoType = true;
force force ace_ui_commandMenu = true;
force ace_ui_enableSpeedIndicator = true;
force force ace_ui_firingMode = true;
force force ace_ui_groupBar = false;
force force ace_ui_gunnerAmmoCount = true;
force force ace_ui_gunnerAmmoType = true;
force force ace_ui_gunnerFiringMode = true;
force force ace_ui_gunnerLaunchableCount = true;
force force ace_ui_gunnerLaunchableName = true;
force force ace_ui_gunnerMagCount = true;
force force ace_ui_gunnerWeaponLowerInfoBackground = true;
force force ace_ui_gunnerWeaponName = true;
force force ace_ui_gunnerWeaponNameBackground = true;
force force ace_ui_gunnerZeroing = true;
ace_ui_hideDefaultActionIcon = false;
force force ace_ui_magCount = true;
force force ace_ui_soldierVehicleWeaponInfo = true;
force force ace_ui_staminaBar = true;
force force ace_ui_stance = true;
force force ace_ui_throwableCount = false;
force force ace_ui_throwableName = true;
force force ace_ui_vehicleAltitude = true;
force force ace_ui_vehicleCompass = true;
force force ace_ui_vehicleDamage = true;
force force ace_ui_vehicleFuelBar = true;
force force ace_ui_vehicleInfoBackground = true;
force force ace_ui_vehicleName = false;
force force ace_ui_vehicleNameBackground = true;
force force ace_ui_vehicleRadar = true;
force force ace_ui_vehicleSpeed = true;
force force ace_ui_weaponLowerInfoBackground = true;
force force ace_ui_weaponName = true;
force force ace_ui_weaponNameBackground = true;
force force ace_ui_zeroing = true;

// ACE Vehicle Lock
force ace_vehiclelock_defaultLockpickStrength = 10;
force ace_vehiclelock_lockVehicleInventory = false;
force ace_vehiclelock_vehicleStartingLockState = -1;

// ACE Vehicles
force ace_novehicleclanlogo_enabled = false;
ace_vehicles_hideEjectAction = true;
force force ace_vehicles_keepEngineRunning = true;
ace_vehicles_speedLimiterStep = 5;
force ace_viewports_enabled = true;

// ACE View Distance Limiter
force ace_viewdistance_enabled = true;
force ace_viewdistance_limitViewDistance = 10000;
ace_viewdistance_objectViewDistanceCoeff = 0;
ace_viewdistance_viewDistanceAirVehicle = 0;
ace_viewdistance_viewDistanceLandVehicle = 0;
ace_viewdistance_viewDistanceOnFoot = 0;

// ACE View Restriction
force acex_viewrestriction_mode = 0;
force acex_viewrestriction_modeSelectiveAir = 0;
force acex_viewrestriction_modeSelectiveFoot = 0;
force acex_viewrestriction_modeSelectiveLand = 0;
force acex_viewrestriction_modeSelectiveSea = 0;
acex_viewrestriction_preserveView = false;

// ACE Volume
force force acex_volume_enabled = true;
force force acex_volume_fadeDelay = 1;
force force acex_volume_lowerInVehicles = true;
force force acex_volume_reduction = 5;
force force acex_volume_remindIfLowered = true;
force force acex_volume_showNotification = true;

// ACE Weapons
force force ace_common_persistentLaserEnabled = true;
force force ace_reload_displayText = true;
ace_reload_showCheckAmmoSelf = false;
ace_reloadlaunchers_displayStatusText = true;
force force ace_weaponselect_displayText = true;

// ACE Weather
force force ace_weather_enabled = true;
force force ace_weather_showCheckAirTemperature = true;
force force ace_weather_updateInterval = 120;
force force ace_weather_windSimulation = true;

// ACE Wind Deflection
force force ace_winddeflection_enabled = true;
force ace_winddeflection_simulationInterval = 0.05;
force force ace_winddeflection_vehicleEnabled = true;

// ACE Zeus
force force ace_zeus_autoAddObjects = true;
force ace_zeus_canCreateZeus = -1;
force ace_zeus_radioOrdnance = false;
force ace_zeus_remoteWind = false;
force force ace_zeus_revealMines = 1;
force ace_zeus_zeusAscension = false;
force force ace_zeus_zeusBird = false;

// AH-64D Official Project
fza_ah64_aiFireControl = true;
fza_ah64_aiFireResponse = 15;
fza_ah64_aiFloodlight = false;
fza_ah64_enableClickHelper = true;
fza_ah64_freeCursorfreelooklock = true;
fza_ah64_freeCursorSensitivity = 0.05;
fza_ah64_LMCSensitivity = 0.5;
fza_ah64_sfmPlusAutoPedal = false;
fza_ah64_sfmPlusAutoPedalTimeScalar = 1.5;
fza_ah64_sfmPlusCollectiveControl = 1;
fza_ah64_sfmplusEnvironment = 1;
fza_ah64_sfmPlusKeyboardStickyPitch = false;
fza_ah64_sfmPlusKeyboardStickyRoll = false;
fza_ah64_sfmPlusKeyboardStickyYaw = false;
fza_ah64_sfmPlusMouseAsJoystick = false;
fza_ah64_sfmPlusMouseSense = 1;
fza_ah64_sfmPlusSpringlessCyclic = false;
fza_ah64_sfmPlusSpringlessPedals = false;
fza_ah64_sfmPlusVrsWarning = false;
fza_ah64_showPopupv2_2 = true;
fza_ah64_tadsCycleIncludeDTV = true;
fza_ah64_tadsCycleIncludeDVO = true;
fza_ah64_vanillaTargetingEnable = true;
fza_ah64_volumeMaster = 3;
fza_ah64_volumeRlwr = 3;
fza_sfmplus_cyclicCenterTrimMode = false;
fza_sfmplus_pedalCenterTrimMode = false;

// Backpack On Chest
force bocr_main_disabled = false;
force bocr_main_walk = true;

// Community Base Addons
cba_diagnostic_ConsoleIndentType = -1;
force cba_diagnostic_watchInfoRefreshRate = 0.2;
cba_disposable_dropUsedLauncher = 2;
force cba_disposable_replaceDisposableLauncher = true;
cba_events_repetitionMode = 1;
force cba_network_loadoutValidation = 0;
cba_optics_usePipOptics = true;
cba_quicktime_qteShorten = false;
cba_ui_notifyLifetime = 4;
cba_ui_StorePasswords = 1;

// DUI - Squad Radar - Indicators
force diwako_dui_indicators_crew_range_enabled = false;
diwako_dui_indicators_fov_scale = false;
diwako_dui_indicators_icon_buddy = true;
diwako_dui_indicators_icon_leader = true;
diwako_dui_indicators_icon_medic = true;
diwako_dui_indicators_range = 20;
diwako_dui_indicators_range_crew = 300;
diwako_dui_indicators_range_scale = false;
force diwako_dui_indicators_rangeLimit = 100;
diwako_dui_indicators_show = true;
diwako_dui_indicators_size = 1;
diwako_dui_indicators_style = "standard";
diwako_dui_indicators_useACENametagsRange = true;

// DUI - Squad Radar - Line Compass
diwako_dui_linecompass_ACEFingeringColor = [1,0.66,0,1];
force diwako_dui_linecompass_AllowNumericDrawBearing = true;
diwako_dui_linecompass_CompassAvailableShown = true;
diwako_dui_linecompass_compassRange = 35;
force diwako_dui_linecompass_compassRangeLimit = 50;
diwako_dui_linecompass_CustomWaypointColor = [0,0,0.87,1];
diwako_dui_linecompass_DefaultIconColor = [0.5,0.87,0.5,1];
diwako_dui_linecompass_DrawBearing = 2;
diwako_dui_linecompass_Enabled = true;
diwako_dui_linecompass_enableOcclusion = false;
diwako_dui_linecompass_IconOutline = 0;
diwako_dui_linecompass_occlusionFadeSpeed = 3.5;
diwako_dui_linecompass_showSpeaking = true;
diwako_dui_linecompass_SwapOrder = false;
diwako_dui_linecompass_WaypointColor = [0,0,0.87,1];

// DUI - Squad Radar - Main
diwako_dui_ace_hide_interaction = true;
diwako_dui_colors = "standard";
diwako_dui_font = "RobotoCondensed";
diwako_dui_icon_style = "standard";
diwako_dui_main_hide_dialog = true;
diwako_dui_main_hide_ui_by_default = false;
diwako_dui_main_squadBlue = [0,0,1,1];
diwako_dui_main_squadGreen = [0,1,0,1];
diwako_dui_main_squadMain = [1,1,1,1];
diwako_dui_main_squadRed = [1,0,0,1];
diwako_dui_main_squadYellow = [1,1,0,1];
diwako_dui_main_trackingColor = [0.93,0.26,0.93,1];
diwako_dui_reset_ui_pos = false;

// DUI - Squad Radar - Nametags
diwako_dui_nametags_customRankStyle = "[[""PRIVATE"",""CORPORAL"",""SERGEANT"",""LIEUTENANT"",""CAPTAIN"",""MAJOR"",""COLONEL""],[""Pvt."",""Cpl."",""Sgt."",""Lt."",""Capt."",""Maj."",""Col.""]]";
diwako_dui_nametags_deadColor = [0.2,0.2,0.2,1];
diwako_dui_nametags_deadRenderDistance = 3.5;
force force diwako_dui_nametags_drawRank = false;
diwako_dui_nametags_enabled = true;
diwako_dui_nametags_enableFOVBoost = true;
diwako_dui_nametags_enableOcclusion = true;
diwako_dui_nametags_fadeInTime = 0.05;
diwako_dui_nametags_fadeOutTime = 0.5;
diwako_dui_nametags_fontGroup = "RobotoCondensedLight";
diwako_dui_nametags_fontGroupNameSize = 8;
diwako_dui_nametags_fontName = "RobotoCondensedBold";
diwako_dui_nametags_fontNameSize = 10;
diwako_dui_nametags_groupColor = [1,1,1,1];
diwako_dui_nametags_groupFontShadow = 1;
diwako_dui_nametags_groupNameOtherGroupColor = [0.6,0.85,0.6,1];
diwako_dui_nametags_nameFontShadow = 1;
diwako_dui_nametags_nameOtherGroupColor = [0.2,1,0,1];
diwako_dui_nametags_rankNameStyle = "default";
diwako_dui_nametags_renderDistance = 40;
force force diwako_dui_nametags_showUnconAsDead = false;
diwako_dui_nametags_useLIS = true;
diwako_dui_nametags_useSideIsFriendly = true;

// DUI - Squad Radar - Radar
diwako_dui_compass_hide_alone_group = false;
diwako_dui_compass_hide_blip_alone_group = false;
diwako_dui_compass_icon_scale = 1;
diwako_dui_compass_opacity = 1;
force force diwako_dui_compass_style = ["\z\diwako_dui\addons\radar\UI\compass_styles\classic\limited.paa","\z\diwako_dui\addons\radar\UI\compass_styles\classic\full.paa"];
force force diwako_dui_compassRange = 50;
diwako_dui_compassRefreshrate = 0;
diwako_dui_dir_showMildot = false;
diwako_dui_dir_size = 1.25;
force force diwako_dui_distanceWarning = 10;
force force diwako_dui_enable_compass = true;
force force diwako_dui_enable_compass_dir = 2;
force force diwako_dui_enable_occlusion = false;
force force diwako_dui_enable_occlusion_cone = 360;
diwako_dui_hudScaling = 1.33333;
diwako_dui_namelist = true;
diwako_dui_namelist_bg = 0;
diwako_dui_namelist_only_buddy_icon = false;
diwako_dui_namelist_size = 1.5396;
diwako_dui_namelist_text_shadow = 2;
diwako_dui_namelist_width = 215;
force force diwako_dui_radar_ace_finger = true;
force force diwako_dui_radar_ace_medic = true;
diwako_dui_radar_always_show_unit_numbers = false;
force force diwako_dui_radar_compassRangeCrew = 500;
force diwako_dui_radar_compassRangeLimit = 50;
diwako_dui_radar_dir_padding = 25;
diwako_dui_radar_dir_shadow = 2;
diwako_dui_radar_enable_seat_icons = 2;
diwako_dui_radar_group_by_vehicle = false;
diwako_dui_radar_icon_opacity = 1;
diwako_dui_radar_icon_opacity_no_player = true;
force diwako_dui_radar_icon_priority_setting = 1;
diwako_dui_radar_icon_scale_crew = 6;
force force diwako_dui_radar_leadingZeroes = true;
diwako_dui_radar_namelist_hideWhenLeader = false;
diwako_dui_radar_namelist_vertical_spacing = 0.75;
diwako_dui_radar_occlusion_fade_in_time = 1;
diwako_dui_radar_occlusion_fade_time = 10;
diwako_dui_radar_pointer_color = [1,0.5,0,1];
diwako_dui_radar_pointer_style = "standard";
force force diwako_dui_radar_show_cardinal_points = true;
force force diwako_dui_radar_showSpeaking = true;
force force diwako_dui_radar_showSpeaking_radioOnly = false;
force force diwako_dui_radar_showSpeaking_replaceIcon = true;
force force diwako_dui_radar_sortType = "fireteam2";
force force diwako_dui_radar_sqlFirst = true;
force diwako_dui_radar_syncGroup = false;
force diwako_dui_radar_vehicleCompassEnabled = false;
diwako_dui_use_layout_editor = false;

// GRAD Trenches
force grad_trenches_functions_allowBigEnvelope = true;
force grad_trenches_functions_allowCamouflage = true;
force grad_trenches_functions_allowDigging = true;
force grad_trenches_functions_allowEffects = true;
force grad_trenches_functions_allowGiantEnvelope = true;
force grad_trenches_functions_allowHitDecay = true;
force grad_trenches_functions_allowLongEnvelope = true;
force grad_trenches_functions_allowShortEnvelope = true;
force grad_trenches_functions_allowSmallEnvelope = true;
force grad_trenches_functions_allowTextureLock = true;
force grad_trenches_functions_allowTrenchDecay = false;
force grad_trenches_functions_allowVehicleEnvelope = true;
force grad_trenches_functions_bigEnvelopeDamageMultiplier = 2;
force grad_trenches_functions_bigEnvelopeDigTime = 40;
force grad_trenches_functions_bigEnvelopeRemovalTime = -1;
force grad_trenches_functions_buildFatigueFactor = 1;
force grad_trenches_functions_camouflageRequireEntrenchmentTool = true;
force grad_trenches_functions_createTrenchMarker = false;
force grad_trenches_functions_decayTime = 1800;
force grad_trenches_functions_giantEnvelopeDamageMultiplier = 1;
force grad_trenches_functions_giantEnvelopeDigTime = 90;
force grad_trenches_functions_giantEnvelopeRemovalTime = -1;
force grad_trenches_functions_hitDecayMultiplier = 1;
force grad_trenches_functions_LongEnvelopeDigTime = 100;
force grad_trenches_functions_LongEnvelopeRemovalTime = -1;
force grad_trenches_functions_playersInAreaRadius = 0;
force grad_trenches_functions_shortEnvelopeDamageMultiplier = 2;
force grad_trenches_functions_shortEnvelopeDigTime = 15;
force grad_trenches_functions_shortEnvelopeRemovalTime = -1;
force grad_trenches_functions_smallEnvelopeDamageMultiplier = 3;
force grad_trenches_functions_smallEnvelopeDigTime = 30;
force grad_trenches_functions_smallEnvelopeRemovalTime = -1;
force grad_trenches_functions_stopBuildingAtFatigueMax = true;
force grad_trenches_functions_textureLockDistance = 5;
force grad_trenches_functions_timeoutToDecay = 7200;
force grad_trenches_functions_vehicleEnvelopeDamageMultiplier = 1;
force grad_trenches_functions_vehicleEnvelopeDigTime = 120;
force grad_trenches_functions_vehicleEnvelopeRemovalTime = -1;
force grad_trenches_functions_vehicleTrenchBuildSpeed = 5;

// Hatchet Vehicle Framework
vxf_interaction_autoclose_actionmenu = false;
vxf_interaction_pointing = true;
vxf_interaction_showDebugMessages = false;
vxf_interaction_showLabels = 2;
vxf_interaction_updateEvery = 5;

// KAT - ADV Medical: Airway
force kat_airway_Accuvac_time = 4;
force kat_airway_autoTriage = true;
force kat_airway_block_headTurning_ifAirwayItem = true;
force kat_airway_CancelRecoveryPosition_Time = 6;
force kat_airway_CheckAirway_time = 2;
force kat_airway_checkbox_puking_sound = true;
force kat_airway_enable = true;
force kat_airway_Guedeltubus_time = 4.1;
force kat_airway_HeadTurn_Interval = 3;
force kat_airway_Hyperextend_Time = 3;
force kat_airway_Larynxtubus_time = 2;
force kat_airway_medLvl_Accuvac = 2;
force kat_airway_medLvl_Guedeltubus = 1;
force kat_airway_medLvl_Larynxtubus = 2;
force kat_airway_medLvl_Suction = 0;
force kat_airway_occlusion_cooldownPeriod = 6;
force kat_airway_occlusion_repeatTimer = 60;
force kat_airway_probability_headturning = 50;
force kat_airway_probability_obstruction = 15;
force kat_airway_probability_occluded = 10;
force kat_airway_RecoveryPosition_Time = 6;
force kat_airway_RecoveryPosition_TimeToDrain = 5;
force kat_airway_ReusableAirwayItems = true;
force kat_airway_string_exit = "";
force kat_airway_Suction_reuse = true;
force force kat_airway_Suction_time = 8;

// KAT - ADV Medical: Breathing
force kat_breathing_advPtxChance = 5;
force kat_breathing_advPtxEnable = false;
force kat_breathing_arrestPneumothorax_interval = 30;
force kat_breathing_availOxyHelmet = "'H_PilotHelmetFighter_B', 'H_PilotHelmetFighter_O', 'H_PilotHelmetFighter_I', 'H_PilotHelmetFighter_I_E'";
force kat_breathing_availOxyMask = "'kat_mask_solr'";
force kat_breathing_BVMOxygen_Multiplier = 1;
force kat_breathing_clearChestSealAfterTreatment = true;
force kat_breathing_deepPenetratingInjuryChance = 15;
force kat_breathing_deterioratingPneumothorax_chance = 10;
force kat_breathing_deterioratingPneumothorax_interval = 60;
force kat_breathing_enable = true;
force kat_breathing_enable_selfChestseal = 1;
force kat_breathing_enableCheckBreathing = true;
force force kat_breathing_Etco2_Enabled = false;
force kat_breathing_Etco2_Units = 0;
force kat_breathing_HPTXBleedAmount = 0.06;
force kat_breathing_hptxChance = 5;
force kat_breathing_inspectChest_enable = 0;
force kat_breathing_inspectChest_medLvl = 0;
force kat_breathing_inspectChest_time = 6;
force kat_breathing_locationProvideOxygen = 3;
force kat_breathing_medLvl_BVM = 1;
force kat_breathing_medLvl_BVM_Oxygen = 1;
force kat_breathing_medLvl_Chestseal = 0;
force kat_breathing_medLvl_hemopneumothoraxTreatment = 0;
force kat_breathing_medLvl_NasalCannula = 0;
force kat_breathing_medLvl_PocketBVM = 0;
force kat_breathing_medLvl_Pulseoximeter = 0;
force kat_breathing_mildValue = 75;
force kat_breathing_NasalCannula_time = 3;
force kat_breathing_paco2Active = false;
force kat_breathing_PneumothoraxAlwaysVisible = true;
force kat_breathing_PneumothoraxArrest = true;
force kat_breathing_pneumothoraxChance = 10;
force kat_breathing_pneumothoraxDamageThreshold = 0.5;
force kat_breathing_pneumothoraxDamageThreshold_TakenDamage = true;
force kat_breathing_PortableOxygenTank_RefillTime = 5;
force kat_breathing_PulseOximeter_SpO2Warning = 70;
force kat_breathing_severeValue = 66;
force kat_breathing_showCyanosis = true;
force kat_breathing_showPneumothorax_dupe = true;
force kat_breathing_slightValue = 90;
force kat_breathing_SpO2_cardiacActive = true;
force kat_breathing_SpO2_cardiacValue = 65;
force kat_breathing_SpO2_dieActive = true;
force kat_breathing_SpO2_dieValue = 60;
force kat_breathing_SpO2_MultiplyNegative = 1;
force kat_breathing_SpO2_MultiplyPositive = 2;
force kat_breathing_SpO2_perfusion = false;
force kat_breathing_SpO2_PerfusionMultiplier = 1;
force kat_breathing_SpO2_unconscious = 70;
force kat_breathing_Stable_spo2 = 80.25;
force kat_breathing_staminaLossAtLowSPO2 = false;
force kat_breathing_stethoscopeListeningTime = 15;
kat_breathing_stethoscopeSoundVolume = 2;
force kat_breathing_TensionHemothoraxAlwaysVisible = true;

// KAT - ADV Medical: Chemical
force kat_chemical_availGasmask = "'G_AirPurifyingRespirator_01_F', 'kat_mask_M50', 'kat_mask_M04'";
force kat_chemical_gasmask_durability = 1200;
kat_chemical_gasMaskSoundVolume = 1;
force kat_chemical_infectionTime = 60;
force kat_chemical_maskStaminaLoss = false;
force kat_chemical_showPoisoning = true;
force kat_chemical_tearGasDropChance = 0;

// KAT - ADV Medical: Circulation
force kat_circulation_abgEnable = false;
force kat_circulation_AdvRhythm = true;
force kat_circulation_AdvRhythm_AED_ROSC_Chance = 70;
force kat_circulation_AdvRhythm_asystoleBloodlossThreshold = 3.6;
force kat_circulation_AdvRhythm_canDeteriorate = true;
force kat_circulation_AdvRhythm_CPR_ROSC_Chance = 35;
force kat_circulation_AdvRhythm_deteriorateAfterTreatment = true;
force kat_circulation_AdvRhythm_deteriorateTimeMax = 900;
force kat_circulation_AdvRhythm_deteriorateTimeWeight = 180;
force kat_circulation_AdvRhythm_Hardcore_Enable = false;
force kat_circulation_AdvRhythm_hardcoreDeteriorationChance = 10;
force kat_circulation_AdvRhythm_HTHold = false;
force kat_circulation_AdvRhythm_PEAChance = 50;
force kat_circulation_AdvRhythm_PEAEnabled = false;
force kat_circulation_AdvRhythm_VTChance = 50;
force kat_circulation_AED_duringCpr = true;
force kat_circulation_AED_MaxChance = 80;
force kat_circulation_AED_MinChance = 40;
force kat_circulation_AED_X_MaxChance = 90;
force kat_circulation_AED_X_MinChance = 70;
force kat_circulation_AED_X_Monitor_SpO2Warning = 70;
force kat_circulation_AED_X_VitalsMonitor_BloodPressureInterval = 0;
force kat_circulation_AED_X_VitalsMonitor_BloodPressureInterval_Time = 30;
force kat_circulation_AED_X_VitalsMonitor_SoundsSelect = 1;
force kat_circulation_AEDX_VitalsMonitor_AttachTime = 2;
force kat_circulation_AEDX_VitalsMonitor_DetachTime = 2;
force kat_circulation_blood_draw_limit = 3.6;
force kat_circulation_blood_drawTime_250ml = 25;
force kat_circulation_blood_drawTime_500ml = 50;
force kat_circulation_bloodGroups = true;
force kat_circulation_bloodTypeCustomList = "O_N";
force kat_circulation_bloodTypeRandomWeighted = false;
force kat_circulation_bloodTypeSetting = 5;
kat_circulation_bloodTypeSettingPlayer = "O_N";
force kat_circulation_cardiacArrestBleedRate = 0.05;
force kat_circulation_CPR_ChanceInterval = 10;
force kat_circulation_CPR_MaxChance_Default = 30;
force kat_circulation_CPR_MaxChance_Doctor = 45;
force kat_circulation_CPR_MaxChance_RegularMedic = 35;
force kat_circulation_CPR_MinChance_Default = 30;
force kat_circulation_CPR_MinChance_Doctor = 35;
force kat_circulation_CPR_MinChance_RegularMedic = 35;
force kat_circulation_CPR_OxygenationPeriod = 10;
force kat_circulation_Defibrillator_DistanceLimit = 6;
force kat_circulation_DefibrillatorPads_AttachTime = 4;
force kat_circulation_DefibrillatorPads_DetachTime = 1;
force kat_circulation_deterioratingTamponade_chance = 35;
force kat_circulation_deterioratingTamponade_interval = 60;
force kat_circulation_enable = true;
force kat_circulation_enable_CPR_Chances = true;
force kat_circulation_enable_selfBloodDraw = 0;
force kat_circulation_hardcoreDiagnose = false;
force kat_circulation_medLvl_AED = 1;
force kat_circulation_medLvl_AED_Station_Interact = 0;
force kat_circulation_medLvl_AED_X = 2;
force kat_circulation_medLvl_BPCuff = 0;
force kat_circulation_medLvl_StethHR = 0;
force kat_circulation_tamponadeChance = 10;
force kat_circulation_treatmentTime_BPCuff = 12;
force kat_circulation_treatmentTime_StethHR = 8;
force kat_circulation_useLocation_AED = 0;

// KAT - ADV Medical: Feedback
force kat_feedback_effectLowSpO2 = 90;
force kat_feedback_enableOpioidEffect = true;

// KAT - ADV Medical: GUI
force force kat_gui_ColoredLogs = true;
force force kat_gui_showPatientSideLabels = true;

// KAT - ADV Medical: Hypothermia
force kat_hypothermia_hypothermiaActive = false;

// KAT - ADV Medical: Misc
kat_misc_AFAK_Container = 0;
kat_misc_AFAK_Item_Color = [0.67,0.84,0.9];
force kat_misc_AFAK_RemoveWhenEmpty = true;
kat_misc_AFAK_Slot_Color = [1,0.96,0.32];
force kat_misc_AFAKFifthSlotItem = "[['kat_guedel', 3]]";
force kat_misc_AFAKFirstSlotItem = "[['ACE_tourniquet', 4], ['ACE_splint', 2]]";
force kat_misc_AFAKFourthSlotItem = "[['kat_chestSeal', 4], ['kat_ncdKit', 4]]";
force kat_misc_AFAKSecondSlotItem = "[['ACE_packingBandage', 10], ['ACE_quikclot', 10]]";
force kat_misc_AFAKSixthSlotItem = "[['ACE_morphine', 3], ['ACE_epinephrine', 3]]";
force kat_misc_AFAKThirdSlotItem = "[['kat_Penthrox', 2], ['kat_Painkiller', 1]]";
force force kat_misc_allowSharedVehicleEquipment = 4;
kat_misc_armbandSlingLeftArm = "0.2, -0.39, -0.2";
kat_misc_armbandSlingLeftArmRotation = "240, 33, 26";
kat_misc_armbandSlingLeftLeg = "0.435, -0.075, -0.38";
kat_misc_armbandSlingLeftLegRotation = "-160, -5, 45";
kat_misc_armbandSlingRightArm = "-0.228, -0.1, -0.43";
kat_misc_armbandSlingRightArmRotation = "5, -5, -5";
kat_misc_armbandSlingRightLeg = "-0.32, -0.29, -0.42";
kat_misc_armbandSlingRightLegRotation = "-30, -5, 38";
force kat_misc_enable = true;
force kat_misc_enableStitchFullBody = true;
kat_misc_IFAK_Container = 0;
kat_misc_IFAK_Item_Color = [0.67,0.84,0.9];
force kat_misc_IFAK_RemoveWhenEmpty = true;
kat_misc_IFAK_Slot_Color = [1,0.3,0.3];
force kat_misc_IFAKFirstSlotItem = "[['ACE_tourniquet', 2]]";
force kat_misc_IFAKFourthSlotItem = "[['kat_chestSeal', 1]]";
force kat_misc_IFAKSecondSlotItem = "[['ACE_packingBandage', 5], ['ACE_quikclot', 5]]";
force kat_misc_IFAKThirdSlotItem = "[['kat_Painkiller', 1]]";
force kat_misc_incompatibilityWarning = true;
kat_misc_MFAK_Container = 0;
kat_misc_MFAK_Item_Color = [0.67,0.84,0.9];
force kat_misc_MFAK_RemoveWhenEmpty = true;
kat_misc_MFAK_Slot_Color = [0.56,0.93,0.56];
force kat_misc_MFAKEighthSlotItem = "[['kat_Pulseoximeter', 3], ['kat_pocketBVM', 1]]";
force kat_misc_MFAKFifthSlotItem = "[['kat_larynx', 6]]";
force kat_misc_MFAKFirstSlotItem = "[['ACE_tourniquet', 6], ['ACE_splint', 4]]";
force kat_misc_MFAKFourthSlotItem = "[['kat_chestSeal', 6], ['kat_aatKit', 3], ['kat_ncdKit', 3], ['kat_stethoscope', 1]]";
force kat_misc_MFAKSecondSlotItem = "[['ACE_packingBandage', 15], ['ACE_quikclot', 15], ['ACE_fieldDressing', 15]]";
force kat_misc_MFAKSeventhSlotItem = "[['ACE_salineIV_250', 3], ['kat_IV_16', 4]]";
force kat_misc_MFAKSixthSlotItem = "[['ACE_morphine', 6], ['ACE_epinephrine', 6], ['ACE_adenosine', 6]]";
force kat_misc_MFAKThirdSlotItem = "[['kat_Painkiller', 4], ['kat_Penthrox', 4]]";
force kat_misc_tourniquetEffects_Enable = true;
force kat_misc_tourniquetEffects_NegativeMultiplier = 1;
force kat_misc_tourniquetEffects_PositiveMultiplier = 1;
force kat_misc_treatmentTimeDetachTourniquet = 4;

// KAT - ADV Medical: Ophthalmology
force kat_ophthalmology_enable = true;
force kat_ophthalmology_eyeshield_medic_required = 0;
force kat_ophthalmology_eyeshield_treatment_time = 2;
force kat_ophthalmology_eyewash_medic_required = 0;
force kat_ophthalmology_eyewash_treatment_time = 2;
force kat_ophthalmology_probability_dust = 5;
force kat_ophthalmology_probability_dust_heavy = 1;
force kat_ophthalmology_probability_treatment_dust = 20;

// KAT - ADV Medical: Pharmacy
force kat_pharma_allowStackScript_EACA = true;
force kat_pharma_allowStackScript_TXA = true;
force kat_pharma_bandageCycleTime_EACA = 8;
force kat_pharma_bandageCycleTime_TXA = 5;
force kat_pharma_blockChance = 0;
force kat_pharma_carbonateChance = 100;
force kat_pharma_CheckCoag_Location = 0;
force kat_pharma_CheckCoag_MedLevel = 0;
force kat_pharma_CheckCoag_TreatmentTime = 10;
force force kat_pharma_coagulation = false;
force kat_pharma_coagulation_allow_clot_text = true;
force kat_pharma_coagulation_allow_EACA_script = true;
force kat_pharma_coagulation_allow_LargeWounds = true;
force kat_pharma_coagulation_allow_MediumWounds = true;
force kat_pharma_coagulation_allow_MinorWounds = true;
force kat_pharma_coagulation_allow_TXA_script = false;
force kat_pharma_coagulation_allowOnAI = false;
force kat_pharma_coagulation_factor_count = 30;
force kat_pharma_coagulation_factor_limit = 60;
force kat_pharma_coagulation_factor_regenerate_time = 120;
force kat_pharma_coagulation_on_all_Bodyparts = true;
force kat_pharma_coagulation_requireBV = 3.6;
force kat_pharma_coagulation_requireHR = false;
force kat_pharma_coagulation_time = 5;
force kat_pharma_coagulation_time_large = 30;
force kat_pharma_coagulation_time_medium = 20;
force kat_pharma_coagulation_time_minor = 10;
force kat_pharma_coagulation_tourniquetBlock = true;
force kat_pharma_eacaClearTrauma = false;
force kat_pharma_ivCheckLimbDamage = true;
force kat_pharma_IVdrop = 600;
force kat_pharma_IVdropEnable = true;
force kat_pharma_IVflowControl = false;
force kat_pharma_IVreuse = true;
force kat_pharma_keepScriptRunning_EACA = true;
force kat_pharma_keepScriptRunning_TXA = true;
force kat_pharma_kidneyAction = false;
force kat_pharma_MedicationsRequireInsIV = true;
force kat_pharma_medLvl_Amiodarone = 2;
force kat_pharma_medLvl_ApplyIO = 2;
force kat_pharma_medLvl_ApplyIV = 1;
force kat_pharma_medLvl_Atropine = 1;
force kat_pharma_medLvl_Caffeine = 0;
force kat_pharma_medLvl_Carbonate = 0;
force kat_pharma_medLvl_CWMP = 2;
force kat_pharma_medLvl_EACA = 2;
force kat_pharma_medLvl_EpinephrineIV = 2;
force kat_pharma_medLvl_Etomidate = 2;
force kat_pharma_medLvl_Fentanyl = 2;
force kat_pharma_medLvl_Flumezenil = 2;
force kat_pharma_medLvl_Ketamine = 2;
force kat_pharma_medLvl_Lidocaine = 2;
force kat_pharma_medLvl_Lorazepam = 2;
force kat_pharma_medLvl_Nalbuphine = 2;
force kat_pharma_medLvl_Naloxone = 0;
force kat_pharma_medLvl_Nitroglycerin = 2;
force kat_pharma_medLvl_Norepinephrine = 1;
force kat_pharma_medLvl_Penthrox = 2;
force kat_pharma_medLvl_Pervitin = 2;
force kat_pharma_medLvl_Phenylephrine = 2;
force kat_pharma_medLvl_Reorientation = 0;
force kat_pharma_medLvl_TXA = 1;
force kat_pharma_pervitinSpeed = 1.15;
force kat_pharma_Reorientation_Enable = true;
force kat_pharma_Reorientation_Slap = true;
force kat_pharma_reorientationChance = 50;
force kat_pharma_RequireInsIV = true;
force kat_pharma_RequireInsIVBloodDraw = false;
force kat_pharma_staminaMedication = false;
force kat_pharma_treatmentTime_Amiodarone = 2.05;
force kat_pharma_treatmentTime_ApplyIO = 4.01;
force kat_pharma_treatmentTime_ApplyIV = 5;
force kat_pharma_treatmentTime_Atropine = 2;
force kat_pharma_treatmentTime_Caffeine = 4;
force kat_pharma_treatmentTime_Carbonate = 2.02;
force kat_pharma_treatmentTime_CWMP = 7;
force kat_pharma_treatmentTime_EACA = 3;
force kat_pharma_treatmentTime_EpinephrineIV = 7;
force kat_pharma_treatmentTime_Etomidate = 2;
force kat_pharma_treatmentTime_Fentanyl = 7;
force kat_pharma_treatmentTime_Flumazenil = 2;
force kat_pharma_treatmentTime_Ketamine = 7;
force kat_pharma_treatmentTime_Lidocaine = 5;
force kat_pharma_treatmentTime_Lorazepam = 2;
force kat_pharma_treatmentTime_Nalbuphine = 6;
force kat_pharma_treatmentTime_Naloxone = 2;
force kat_pharma_treatmentTime_Nitroglycerin = 4;
force kat_pharma_treatmentTime_Norepinephrine = 4;
force kat_pharma_treatmentTime_Penthrox = 8;
force kat_pharma_treatmentTime_Pervitin = 5;
force kat_pharma_treatmentTime_Phenylephrine = 7;
force kat_pharma_treatmentTime_Reorientation = 2;
force kat_pharma_treatmentTime_TXA = 3;
force kat_pharma_weapon_sway_pervitin = true;

// KAT - ADV Medical: Surgery
force kat_surgery_closedLocation = 0;
force kat_surgery_closedReduction_MedLevel = 2;
force kat_surgery_closedReductionFailChance = 10;
force kat_surgery_closedTime = 10;
force kat_surgery_compoundChance = 30;
force kat_surgery_enable_fracture = false;
force kat_surgery_enable_selfCheckFracture = 1;
force kat_surgery_fractureCheck_MedLevel = 0;
force kat_surgery_fractureCheck_Time = 10;
force kat_surgery_incisionTime = 10;
force kat_surgery_intermediateTime = 8;
force kat_surgery_npwt_MedLevel = 2;
force kat_surgery_npwtLocation = 0;
force kat_surgery_npwtTime = 2;
force kat_surgery_openTime = 15;
force kat_surgery_pericardialtap_MedLevel = 2;
force kat_surgery_pericardialtapLocation = 3;
force kat_surgery_pericardialtapTime = 8;
force kat_surgery_reboa_MedLevel = 2;
force kat_surgery_reboaLocation = 3;
force kat_surgery_reboaTime = 8;
force kat_surgery_simpleChance = 60;
force kat_surgery_Surgery_ConsciousnessRequirement = 1;
force kat_surgery_surgicalAction_MedLevel = 2;
force kat_surgery_surgicalLocation = 3;
force kat_surgery_ultrasound_MedLevel = 2;
force kat_surgery_ultrasoundLocation = 3;
force kat_surgery_ultrasoundTime = 8;

// KAT - ADV Medical: Vitals
force kat_vitals_basicDiagnosticTime = 8;
force kat_vitals_enableBasicDiagnostic = true;
force kat_vitals_enableFluidShift = true;
force force kat_vitals_enableSimpleMedical = true;

// KAT - ADV Medical: Watch
force kat_watch_altitudeUnit = 0;
force kat_watch_pressureUnit = 0;
force kat_watch_temperatureUnit = 0;
force kat_watch_watchInaccuracy = false;

// LAMBS Danger
force lambs_danger_cqbRange = 60;
lambs_danger_disableAIAutonomousManoeuvres = false;
lambs_danger_disableAIDeployStaticWeapons = false;
lambs_danger_disableAIFindStaticWeapons = false;
lambs_danger_disableAIHideFromTanksAndAircraft = false;
lambs_danger_disableAIPlayerGroup = false;
lambs_danger_disableAIPlayerGroupReaction = false;
lambs_danger_disableAutonomousFlares = false;
lambs_danger_disableAutonomousSmokeGrenades = false;
force lambs_danger_panicChance = 0.1;

// LAMBS Danger Eventhandlers
force lambs_eventhandlers_ExplosionEventHandlerEnabled = true;
force lambs_eventhandlers_ExplosionReactionTime = 9;

// LAMBS Danger WP
force lambs_wp_autoAddArtillery = false;

// LAMBS Main
force lambs_main_combatShareRange = 200;
force lambs_main_debug_drawAllUnitsInVehicles = false;
force lambs_main_debug_Drawing = false;
force lambs_main_debug_FSM = false;
force lambs_main_debug_FSM_civ = false;
force lambs_main_debug_functions = false;
force lambs_main_debug_RenderExpectedDestination = false;
lambs_main_disableAICallouts = false;
lambs_main_disableAIDodge = false;
lambs_main_disableAIFleeing = false;
lambs_main_disableAIGestures = false;
lambs_main_disableAutonomousMunitionSwitching = false;
lambs_main_disablePlayerGroupSuppression = false;
force lambs_main_indoorMove = 0.1;
force lambs_main_maxRevealValue = 1;
force lambs_main_minFriendlySuppressionDistance = 5;
force lambs_main_minObstacleProximity = 5;
force lambs_main_minSuppressionRange = 50;
force lambs_main_radioBackpack = 2000;
lambs_main_radioDisabled = false;
force lambs_main_radioEast = 500;
force lambs_main_radioGuer = 500;
force lambs_main_radioShout = 100;
force lambs_main_radioWest = 500;

// TFAR - Clientside settings
force force TFAR_curatorCamEars = false;
TFAR_default_radioVolume = 6;
TFAR_intercomDucking = 0.2;
TFAR_intercomVolume = 0.1;
TFAR_moveWhileTabbedOut = false;
TFAR_noAutomoveSpectator = false;
TFAR_oldVolumeHint = false;
TFAR_pluginTimeout = 4;
TFAR_PosUpdateMode = 0.2;
TFAR_showChannelChangedHint = true;
force force TFAR_ShowDiaryRecord = false;
TFAR_showTransmittingHint = true;
TFAR_ShowVolumeHUD = false;
TFAR_splendidCamEars = false;
TFAR_tangentReleaseDelay = 0;
TFAR_VolumeHudTransparency = 0;
TFAR_volumeModifier_forceSpeech = false;

// TFAR - Global settings
force force TFAR_AICanHearPlayer = true;
force force TFAR_AICanHearSpeaker = true;
force force TFAR_allowDebugging = false;
force force tfar_core_noTSNotConnectedHint = false;
force force TFAR_defaultIntercomSlot = 0;
force force TFAR_disableAutoMute = false;
force force TFAR_enableIntercom = true;
force force TFAR_experimentalVehicleIsolation = false;
force TFAR_externalIntercomEnable = 0;
force TFAR_externalIntercomMaxRange_Phone = 5;
force TFAR_externalIntercomMaxRange_Wireless = 15;
force force TFAR_fullDuplex = true;
force force TFAR_giveLongRangeRadioToGroupLeaders = false;
force force TFAR_giveMicroDagrToSoldier = true;
force force TFAR_givePersonalRadioToRegularSoldier = false;
force force TFAR_globalRadioRangeCoef = 1;
force force TFAR_instantiate_instantiateAtBriefing = false;
force force TFAR_objectInterceptionEnabled = true;
force force TFAR_objectInterceptionStrength = 400;
force force tfar_radiocode_east = "_opfor";
force force tfar_radiocode_independent = "_independent";
force force tfar_radiocode_west = "_bluefor";
force force tfar_radioCodesDisabled = false;
force force TFAR_SameLRFrequenciesForSide = false;
force force TFAR_SameSRFrequenciesForSide = false;
force force TFAR_setting_defaultFrequencies_lr_east = "";
force force TFAR_setting_defaultFrequencies_lr_independent = "";
force force TFAR_setting_defaultFrequencies_lr_west = "";
force force TFAR_setting_defaultFrequencies_sr_east = "";
force force TFAR_setting_defaultFrequencies_sr_independent = "";
force force TFAR_setting_defaultFrequencies_sr_west = "";
force force TFAR_setting_DefaultRadio_Airborne_east = "TFAR_mr6000l";
force force TFAR_setting_DefaultRadio_Airborne_Independent = "TFAR_anarc164";
force force TFAR_setting_DefaultRadio_Airborne_West = "TFAR_anarc210";
force force TFAR_setting_DefaultRadio_Backpack_east = "TFAR_mr3000";
force force TFAR_setting_DefaultRadio_Backpack_Independent = "TFAR_anprc155";
force force TFAR_setting_DefaultRadio_Backpack_west = "TFAR_rt1523g";
force force TFAR_setting_DefaultRadio_Personal_east = "TFAR_fadak";
force force TFAR_setting_DefaultRadio_Personal_Independent = "TFAR_anprc148jem";
force force TFAR_setting_DefaultRadio_Personal_West = "TFAR_anprc152";
force force TFAR_setting_DefaultRadio_Rifleman_East = "TFAR_pnr1000a";
force force TFAR_setting_DefaultRadio_Rifleman_Independent = "TFAR_anprc154";
force force TFAR_setting_DefaultRadio_Rifleman_West = "TFAR_rf7800str";
force TFAR_setting_externalIntercomWirelessHeadgear = "";
force force TFAR_spectatorCanHearEnemyUnits = true;
force force TFAR_spectatorCanHearFriendlies = true;
force force TFAR_takingRadio = 2;
force force TFAR_Teamspeak_Channel_Name = "Training Grounds";
force force TFAR_Teamspeak_Channel_Password = "InterOP";
force force tfar_terrain_interception_coefficient = 7;
force force TFAR_voiceCone = true;

// Tier 1 Artillery Mod
force T1AM_AllowMapClick = true;
force T1AM_AuthorizedClasses = "";
force T1AM_AuthorizedVariables = "";
force T1AM_AuthorizeEveryone = true;
force T1AM_DEBUG_DisableInitialMiss = false;
force T1AM_DEBUG_DisableRandomSpread = false;
force T1AM_DEBUG_ForceVanillaGrid = false;
force T1AM_Debug_Mode = false;
force T1AM_DEBUG_ShowRounds = false;
force T1AM_ExcludedArtyClasses = "";
force T1AM_ExcludedArtyVariables = "";
force T1AM_ModEnabled = true;
force T1AM_PrepTimes = 1;
force force T1AM_ShowOtherRadioMessages = 1;
force T1AM_ShowTrpMarkers = true;

// UH-60M
force vtx_ace_viv_loadDistance = 15;
force vtx_ace_viv_timeFactor = 1;
vtx_uh60_anvishud_defaultMode = -1;
vtx_uh60_anvishud_settingBrightness = 0.6;
vtx_uh60_anvishud_settingColor = [0.082,0.608,0.039];
vtx_uh60_flir_setting_AimSlewBlockMouse = true;
vtx_uh60_flir_setting_AimSlewSpeed = 1;
vtx_uh60_flir_setting_AimXFactor = 1;
force vtx_uh60_flir_setting_animateTurret = true;
vtx_uh60_flir_setting_KeySlewSpeed = 1;
vtx_uh60_flir_setting_KeyXFactor = 1;
force vtx_uh60_flir_setting_syncDelay = 0.015;
vtx_uh60_hoist_setting_useAttachScript = false;
vtx_uh60_jvmf_defaults = true;
vtx_uh60_sfmPlus_showDamageHints = true;
vtx_uh60_sfmPlusStabilatorEnabled = 1;
vtx_uh60_ui_showDebugMessages = false;
vtx_uh60m_enabled_aar = true;
vtx_uh60m_enabled_cas = true;
vtx_uh60m_enabled_engine = true;
vtx_uh60m_enabled_fd = true;
vtx_uh60m_enabled_flir = true;
vtx_uh60m_enabled_fms = true;
vtx_uh60m_enabled_jvmf = true;
vtx_uh60m_enabled_mfd = true;
vtx_uh60m_simpleCollective = false;
vtx_uh60m_simpleStartup = false;
vtx_uh60m_trackIR_interaction_cursor = false;
vtx_uh60m_trackIR_interaction_cursorSensitivity = 2.5;

// VS Static Line
force VS_ChuteClass = "";
force VS_NODsFriendly = true;
force VS_StaticEquipped = true;

// Zeus Additions
zeus_additions_main_AABLU_mags = "[""rhs_fim92_mag"",""Titan_AA""]";
zeus_additions_main_AARED_mags = "[""rhs_mag_9k38_rocket"",""Titan_AA""]";
zeus_additions_main_blacklistFKEnable = false;
zeus_additions_main_blacklistSettings = "[]";
zeus_additions_main_enableACEDragHint = true;
zeus_additions_main_enableACEMedicalHint = true;
zeus_additions_main_enableBuildingDestructionHandling = false;
zeus_additions_main_enableMissionCounter = false;
zeus_additions_main_enableRHSHint = true;
zeus_additions_main_enableTFARHint = true;
zeus_additions_main_HATBLU_mags = "[""UK3CB_BAF_Javelin_Slung_Tube"",""rhs_fgm148_magazine_AT""]";
zeus_additions_main_HATRED_mags = "[""Vorona_HE"",""Vorona_HEAT""]";
zeus_additions_main_LATBLU_mags = "[""UK3CB_BAF_AT4_CS_AP_Launcher"",""UK3CB_BAF_AT4_CS_AT_Launcher"",""rhs_weap_M136"",""rhs_weap_M136_hedp"",""rhs_weap_M136_hp"",""rhs_weap_m72a7""]";
zeus_additions_main_LATRED_mags = "[""rhs_weap_rpg18"",""rhs_weap_rpg26"",""rhs_weap_rshg2"",""rhs_weap_m80"",""rhs_weap_rpg75""]";
zeus_additions_main_MATBLU_mags = "[""rhs_mag_maaws_HE"",""rhs_mag_maaws_HEAT"",""MRAWS_HE_F"",""MRAWS_HEAT_F"",""rhs_mag_smaw_HEDP"",""rhs_mag_smaw_HEAA""]";
zeus_additions_main_MATRED_mags = "[""rhs_rpg7_OG7V_mag"",""rhs_rpg7_PG7V_mag"",""rhs_rpg7_PG7VL_mag"",""rhs_rpg7_PG7VM_mag"",""rhs_rpg7_PG7VR_mag"",""rhs_rpg7_TBG7V_mag"",""rhs_rpg7_type69_airburst_mag"",""RPG7_F"",""RPG32_HE_F"",""RPG32_F""]";

// Zeus Enhanced
force zen_area_markers_editableMarkers = 0;
zen_building_markers_enabled = false;
zen_camera_adaptiveSpeed = true;
zen_camera_defaultSpeedCoef = 1;
zen_camera_fastSpeedCoef = 1;
zen_camera_followTerrain = true;
force zen_common_ascensionMessages = false;
force zen_common_autoAddObjects = true;
force zen_common_cameraBird = false;
force zen_common_darkMode = true;
force zen_common_disableGearAnim = true;
force zen_common_preferredArsenal = 1;
zen_compat_ace_hideModules = true;
zen_context_menu_enabled = 2;
zen_context_menu_overrideWaypoints = false;
zen_editor_addGroupIcons = false;
zen_editor_addModIcons = false;
zen_editor_declutterEmptyTree = true;
zen_editor_disableLiveSearch = false;
zen_editor_moveDisplayToEdge = true;
force zen_editor_parachuteSounds = true;
force zen_editor_previews_enabled = true;
zen_editor_randomizeCopyPaste = false;
zen_editor_removeWatermark = true;
force zen_editor_unitRadioMessages = 1;
force zen_placement_enabled = false;
zen_remote_control_cameraExitPosition = 2;
zen_visibility_enabled = 0;
zen_visibility_maxDistance = 5000;
zen_vision_enableBlackHot = false;
zen_vision_enableBlackHotGreenCold = false;
zen_vision_enableBlackHotRedCold = false;
zen_vision_enableGreenHotCold = false;
zen_vision_enableNVG = true;
zen_vision_enableRedGreenThermal = false;
zen_vision_enableRedHotCold = false;
zen_vision_enableWhiteHot = true;
zen_vision_enableWhiteHotRedCold = false;

// Zeus Enhanced - Attributes
zen_attributes_enableAbilities = true;
zen_attributes_enableAmmo = true;
zen_attributes_enableAmmoCargo = true;
zen_attributes_enableArsenal = true;
zen_attributes_enableBuildingMarker = true;
zen_attributes_enableDamage = true;
zen_attributes_enableEngine = true;
zen_attributes_enableExecute = true;
zen_attributes_enableFuel = true;
zen_attributes_enableFuelCargo = true;
zen_attributes_enableGarage = true;
zen_attributes_enableGroupBehaviour = true;
zen_attributes_enableGroupCombatMode = true;
zen_attributes_enableGroupExecute = true;
zen_attributes_enableGroupFormation = true;
zen_attributes_enableGroupID = true;
zen_attributes_enableGroupSide = true;
zen_attributes_enableGroupSkill = true;
zen_attributes_enableGroupSpeed = true;
zen_attributes_enableGroupStance = true;
zen_attributes_enableHealth = true;
zen_attributes_enableInventory = true;
zen_attributes_enableLights = true;
zen_attributes_enableMarkerAlpha = true;
zen_attributes_enableMarkerColor = true;
zen_attributes_enableMarkerText = true;
zen_attributes_enableName = true;
zen_attributes_enablePlateNumber = true;
zen_attributes_enableRank = true;
zen_attributes_enableRepairCargo = true;
zen_attributes_enableRespawnPosition = true;
zen_attributes_enableRespawnVehicle = true;
zen_attributes_enableSensors = true;
zen_attributes_enableSkill = true;
zen_attributes_enableSkills = true;
zen_attributes_enableStance = true;
zen_attributes_enableStates = true;
zen_attributes_enableTraits = true;
zen_attributes_enableVehicleLock = true;
zen_attributes_enableWaypointBehaviour = true;
zen_attributes_enableWaypointCombatMode = true;
zen_attributes_enableWaypointFormation = true;
zen_attributes_enableWaypointLoiterAltitude = true;
zen_attributes_enableWaypointLoiterDirection = true;
zen_attributes_enableWaypointLoiterRadius = true;
zen_attributes_enableWaypointSpeed = true;
zen_attributes_enableWaypointTimeout = true;
zen_attributes_enableWaypointType = true;

// Zeus Enhanced - Faction Filter
zen_faction_filter_0_LOP_AFR_OPF = true;
zen_faction_filter_0_LOP_AM_OPF = true;
zen_faction_filter_0_LOP_BH = true;
zen_faction_filter_0_LOP_ChDKZ = true;
zen_faction_filter_0_LOP_IRA = true;
zen_faction_filter_0_LOP_ISTS_OPF = true;
zen_faction_filter_0_LOP_NK = true;
zen_faction_filter_0_LOP_SLA = true;
zen_faction_filter_0_LOP_SYR = true;
zen_faction_filter_0_LOP_TKA = true;
zen_faction_filter_0_LOP_US = true;
zen_faction_filter_0_OPF_F = true;
zen_faction_filter_0_OPF_G_F = true;
zen_faction_filter_0_OPF_GEN_F = true;
zen_faction_filter_0_OPF_R_F = true;
zen_faction_filter_0_OPF_T_F = true;
zen_faction_filter_0_rhs_faction_msv = true;
zen_faction_filter_0_rhs_faction_rva = true;
zen_faction_filter_0_rhs_faction_tv = true;
zen_faction_filter_0_rhs_faction_vdv = true;
zen_faction_filter_0_rhs_faction_vmf = true;
zen_faction_filter_0_rhs_faction_vpvo = true;
zen_faction_filter_0_rhs_faction_vv = true;
zen_faction_filter_0_rhs_faction_vvs = true;
zen_faction_filter_0_rhs_faction_vvs_c = true;
zen_faction_filter_0_rhsgref_faction_chdkz = true;
zen_faction_filter_0_rhsgref_faction_chdkz_groups = true;
zen_faction_filter_0_rhsgref_faction_tla = true;
zen_faction_filter_0_rhssaf_faction_airforce_opfor = true;
zen_faction_filter_0_rhssaf_faction_army_opfor = true;
zen_faction_filter_0_Third_Cat_Units_African_Isis = true;
zen_faction_filter_0_Third_Cat_Units_GSIM = true;
zen_faction_filter_0_Third_Cat_Units_Livonian_AF = true;
zen_faction_filter_0_Third_Cat_Units_Livonian_AF_SF = true;
zen_faction_filter_0_Third_Cat_Units_Malian = true;
zen_faction_filter_0_Third_Cat_Units_Russian_Separatists = true;
zen_faction_filter_0_Third_Cat_Units_Wagner_Group = true;
zen_faction_filter_1_BLU_CTRG_F = true;
zen_faction_filter_1_BLU_F = true;
zen_faction_filter_1_BLU_G_F = true;
zen_faction_filter_1_BLU_GEN_F = true;
zen_faction_filter_1_BLU_T_F = true;
zen_faction_filter_1_BLU_W_F = true;
zen_faction_filter_1_fza_usaav = true;
zen_faction_filter_1_LOP_AA = true;
zen_faction_filter_1_LOP_CDF = true;
zen_faction_filter_1_LOP_GRE = true;
zen_faction_filter_1_LOP_IA = true;
zen_faction_filter_1_LOP_PESH = true;
zen_faction_filter_1_rhs_faction_socom = true;
zen_faction_filter_1_rhs_faction_usaf = true;
zen_faction_filter_1_rhs_faction_usarmy_d = true;
zen_faction_filter_1_rhs_faction_usarmy_wd = true;
zen_faction_filter_1_rhs_faction_usmc_d = true;
zen_faction_filter_1_rhs_faction_usmc_wd = true;
zen_faction_filter_1_rhs_faction_usn = true;
zen_faction_filter_1_rhsgref_faction_cdf_air_b = true;
zen_faction_filter_1_rhsgref_faction_cdf_ground_b = true;
zen_faction_filter_1_rhsgref_faction_cdf_ground_b_groups = true;
zen_faction_filter_1_rhsgref_faction_cdf_ng_b = true;
zen_faction_filter_1_rhsgref_faction_hidf = true;
zen_faction_filter_1_Third_Cat_Units_Malian_Army = true;
zen_faction_filter_2_IND_C_F = true;
zen_faction_filter_2_IND_E_F = true;
zen_faction_filter_2_IND_F = true;
zen_faction_filter_2_IND_G_F = true;
zen_faction_filter_2_IND_L_F = true;
zen_faction_filter_2_LOP_AFR = true;
zen_faction_filter_2_LOP_AM = true;
zen_faction_filter_2_LOP_IRAN = true;
zen_faction_filter_2_LOP_ISTS = true;
zen_faction_filter_2_LOP_NAPA = true;
zen_faction_filter_2_LOP_PESH_IND = true;
zen_faction_filter_2_LOP_PMC = true;
zen_faction_filter_2_LOP_RACS = true;
zen_faction_filter_2_LOP_TRK = true;
zen_faction_filter_2_LOP_UA = true;
zen_faction_filter_2_LOP_UKR = true;
zen_faction_filter_2_LOP_UN = true;
zen_faction_filter_2_LOP_UVF = true;
zen_faction_filter_2_PRACS = true;
zen_faction_filter_2_PRACS_IMAS = true;
zen_faction_filter_2_PRACS_RACS_GROUPS_Advisors = true;
zen_faction_filter_2_rhsgref_faction_cdf_air = true;
zen_faction_filter_2_rhsgref_faction_cdf_ground = true;
zen_faction_filter_2_rhsgref_faction_cdf_ground_groups = true;
zen_faction_filter_2_rhsgref_faction_cdf_ng = true;
zen_faction_filter_2_rhsgref_faction_cdf_ng_groups = true;
zen_faction_filter_2_rhsgref_faction_chdkz_g = true;
zen_faction_filter_2_rhsgref_faction_chdkz_g_groups = true;
zen_faction_filter_2_rhsgref_faction_nationalist = true;
zen_faction_filter_2_rhsgref_faction_nationalist_groups = true;
zen_faction_filter_2_rhsgref_faction_tla_g = true;
zen_faction_filter_2_rhsgref_faction_un = true;
zen_faction_filter_2_rhssaf_faction_airforce = true;
zen_faction_filter_2_rhssaf_faction_army = true;
zen_faction_filter_2_rhssaf_faction_un = true;
zen_faction_filter_2_Third_Cat_Units_Neutral_African = true;
zen_faction_filter_3_CIV_F = true;
zen_faction_filter_3_CIV_IDAP_F = true;
zen_faction_filter_3_EdCat_jbad_vehicles = true;
zen_faction_filter_3_EdCat_Things = true;
zen_faction_filter_3_IND_L_F = true;
zen_faction_filter_3_LOP_AFR_Civ = true;
zen_faction_filter_3_LOP_CHR_Civ = true;
zen_faction_filter_3_LOP_TAK_Civ = true;
zen_faction_filter_3_Third_Cat_Units_3rdID_Civilians = true;

// LAxemanns Suppress
L_Suppress_buildup = 1;
L_Suppress_enabled = true;
L_Suppress_flyByEffects = true;
L_Suppress_flyByIntensity = 1;
L_Suppress_halting = true;
L_Suppress_intensity = 1;
L_Suppress_playerSwabEnabled = true;
L_Suppress_recovery = 1;

// Laxemann Immerse
L_Immerse_exShake = true;
L_Immerse_force = true;
L_Immerse_recoil = true;
L_Immerse_twitch = true;

//Tier 1 Artillery
force force T1AM_ShowOtherRadioMessages = 1;